#!/usr/bin/env bash
# =============================================================================
# CouchDB Seed Script (Document Database)
#
# Showcases: denormalized nested documents, flexible schemas, embedded arrays,
# mixed document types in the same database, and MapReduce views.
#
# Each book is a self-contained document with authors and reviews embedded
# directly — no joins required. Compare this to the normalized Postgres schema
# where the same data spans 6+ tables.
#
# Data: 120 books, 25 customers. Generated from data/books.json + data/customers.json.
# =============================================================================
set -euo pipefail

COUCH_HOST="${COUCH_HOST:-localhost}"
COUCH="http://launchpad:dontdothis@${COUCH_HOST}:5984"

echo "==> Waiting for CouchDB to be ready..."
until curl -sf "${COUCH}/" > /dev/null 2>&1; do
  sleep 1
done
echo "==> CouchDB is up."

# Create the bookstore database (idempotent — CouchDB returns 412 if it exists).
echo "==> Creating 'bookstore' database..."
curl -sf -X PUT "${COUCH}/bookstore" > /dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# Helper: insert a document, skip if already exists (by _id).
# ---------------------------------------------------------------------------
put_doc() {
  local id="$1"
  local json="$2"
  # Check if doc already exists
  if curl -sf "${COUCH}/bookstore/${id}" > /dev/null 2>&1; then
    echo "    (skip) ${id} already exists"
    return
  fi
  curl -sf -X PUT "${COUCH}/bookstore/${id}" \
    -H "Content-Type: application/json" \
    -d "${json}" > /dev/null
  echo "    + ${id}"
}

# ---------------------------------------------------------------------------
# Book documents — notice how authors, reviews, and metadata are all embedded.
# In a relational DB this would require JOINs across books, authors,
# book_authors, reviews, and customers. Here it's a single document read.
# ---------------------------------------------------------------------------
echo "==> Inserting book documents..."

put_doc "book:dune" '{"type": "book", "title": "Dune", "isbn": "978-0441013593", "genre": "Science Fiction", "price": 9.99, "published_date": "1965-08-01", "in_stock": true, "authors": [{"name": "Frank Herbert", "born_year": 1920}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "A masterpiece of science fiction. The world-building is unmatched."}, {"customer": "Bob Smith", "rating": 4, "body": "Dense but rewarding. The political intrigue kept me hooked."}, {"customer": "Elena Rodriguez", "rating": 5, "body": "Changed the way I think about ecology and politics in fiction."}, {"customer": "Keiko Tanaka", "rating": 4, "body": "Epic in scope. Herbert built something truly unique."}, {"customer": "Priya Sharma", "rating": 3, "body": "Ambitious but overwritten. The pacing drags in the middle third."}, {"customer": "Viktor Petrov", "rating": 2, "body": "Too many made-up words and political monologues. I couldn'\''t finish it."}], "tags": ["desert", "politics", "ecology", "epic", "spice"]}'

put_doc "book:the-fellowship-of-the-ring" '{"type": "book", "title": "The Fellowship of the Ring", "isbn": "978-0547928210", "genre": "Fantasy", "price": 12.99, "published_date": "1954-07-29", "in_stock": true, "authors": [{"name": "J.R.R. Tolkien", "born_year": 1892}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "The definitive fantasy epic. Every page is magic."}, {"customer": "Carol Williams", "rating": 5, "body": "Tolkien created a world that feels more real than our own."}, {"customer": "Grace Kim", "rating": 5, "body": "A timeless journey that only gets better with every reread."}, {"customer": "Jamal Washington", "rating": 4, "body": "Beautiful prose, though the pacing can be slow at times."}, {"customer": "Rashid Kouri", "rating": 2, "body": "Endless walking and singing. Where is the plot?"}, {"customer": "Tyler Brooks", "rating": 3, "body": "Respect the craft but it reads like a history textbook at times."}], "tags": ["quest", "elves", "hobbits", "epic", "ring"]}'

put_doc "book:murder-on-the-orient-express" '{"type": "book", "title": "Murder on the Orient Express", "isbn": "978-0062693662", "genre": "Mystery", "price": 10.99, "published_date": "1934-01-01", "in_stock": true, "authors": [{"name": "Agatha Christie", "born_year": 1890}], "reviews": [{"customer": "Bob Smith", "rating": 4, "body": "Classic whodunit. Christie keeps you guessing until the very end."}, {"customer": "Frank Okafor", "rating": 5, "body": "The reveal is one of the most satisfying in all of mystery fiction."}, {"customer": "Iris Novak", "rating": 4, "body": "A perfect locked-room mystery with incredible misdirection."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Clever ending, but the characters all feel like cardboard cutouts."}, {"customer": "Wendy Zhao", "rating": 3, "body": "The solution is brilliant but I guessed it halfway through."}], "tags": ["detective", "train", "whodunit", "poirot"]}'

put_doc "book:foundation" '{"type": "book", "title": "Foundation", "isbn": "978-0553293357", "genre": "Science Fiction", "price": 8.99, "published_date": "1951-06-01", "in_stock": true, "authors": [{"name": "Isaac Asimov", "born_year": 1920}], "reviews": [{"customer": "Carol Williams", "rating": 4, "body": "Asimov'\''s vision of the future is both grand and intimate."}, {"customer": "Hassan Ali", "rating": 5, "body": "Psychohistory is one of the most brilliant sci-fi concepts ever."}, {"customer": "Noah Fischer", "rating": 4, "body": "A bit dry in places, but the ideas are monumental."}, {"customer": "Sofia Andersson", "rating": 2, "body": "All ideas, no characters. Every person talks the same way."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Interesting premise but the writing style feels dated."}], "tags": ["psychohistory", "empire", "mathematics", "civilization"]}'

put_doc "book:the-left-hand-of-darkness" '{"type": "book", "title": "The Left Hand of Darkness", "isbn": "978-0441478125", "genre": "Science Fiction", "price": 11.99, "published_date": "1969-03-01", "in_stock": true, "authors": [{"name": "Ursula K. Le Guin", "born_year": 1929}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "Le Guin challenges everything you think you know about gender."}, {"customer": "Liam O'\''Brien", "rating": 5, "body": "Quietly revolutionary. The prose is spare and beautiful."}, {"customer": "Tyler Brooks", "rating": 3, "body": "Important themes but the plot moves at a glacial pace."}], "tags": ["gender", "anthropology", "winter", "alien", "identity"]}'

put_doc "book:good-omens" '{"type": "book", "title": "Good Omens", "isbn": "978-0060853983", "genre": "Fantasy", "price": 13.99, "published_date": "1990-05-01", "in_stock": true, "authors": [{"name": "Neil Gaiman", "born_year": 1960}, {"name": "Terry Pratchett", "born_year": 1948}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "Hilarious and profound. Gaiman and Pratchett are a perfect duo."}, {"customer": "Bob Smith", "rating": 5, "body": "I'\''ve never laughed this hard at an apocalypse."}, {"customer": "Dan Chen", "rating": 4, "body": "Witty, warm, and surprisingly touching. A comfort read."}, {"customer": "Maya Patel", "rating": 5, "body": "The best comedy fantasy ever written. Fight me."}, {"customer": "Uma Okonkwo", "rating": 3, "body": "Funny in places, but the humor got repetitive for me."}, {"customer": "Yuki Mori", "rating": 2, "body": "Tried really hard to like this. The randomness isn'\''t my thing."}], "tags": ["apocalypse", "humor", "angels", "demons", "comedy"]}'

put_doc "book:american-gods" '{"type": "book", "title": "American Gods", "isbn": "978-0063081918", "genre": "Fantasy", "price": 14.99, "published_date": "2001-06-19", "in_stock": true, "authors": [{"name": "Neil Gaiman", "born_year": 1960}], "reviews": [{"customer": "Carol Williams", "rating": 4, "body": "A sprawling American mythology. Gaiman at his best."}, {"customer": "Jamal Washington", "rating": 4, "body": "Atmospheric and strange. It lingers in your mind."}, {"customer": "Priya Sharma", "rating": 2, "body": "Meandering and bloated. I kept waiting for something to happen."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Cool concept, but the middle section really loses momentum."}], "tags": ["mythology", "america", "gods", "road-trip"]}'

put_doc "book:the-color-of-magic" '{"type": "book", "title": "The Color of Magic", "isbn": "978-0062225672", "genre": "Fantasy", "price": 7.99, "published_date": "1983-11-24", "in_stock": true, "authors": [{"name": "Terry Pratchett", "born_year": 1948}], "reviews": [{"customer": "Alice Johnson", "rating": 4, "body": "The Discworld awaits. Pratchett'\''s humor is one of a kind."}, {"customer": "Grace Kim", "rating": 5, "body": "A hilarious send-up of fantasy tropes. Pure Pratchett."}, {"customer": "Sofia Andersson", "rating": 3, "body": "Fun, but Pratchett hadn'\''t found his voice yet. Later books are better."}, {"customer": "Viktor Petrov", "rating": 2, "body": "Just a series of jokes strung together. No real story."}], "tags": ["discworld", "humor", "parody", "wizard", "turtle"]}'

put_doc "book:1984" '{"type": "book", "title": "1984", "isbn": "978-0451524935", "genre": "Fiction", "price": 9.99, "published_date": "1949-06-08", "in_stock": true, "authors": [{"name": "George Orwell", "born_year": 1903}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "Terrifyingly relevant. Orwell saw the future."}, {"customer": "Hassan Ali", "rating": 5, "body": "The most important dystopian novel ever written."}, {"customer": "Olivia Santos", "rating": 4, "body": "Bleak but essential reading. The ending haunts you."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Important message, but the prose is deliberately joyless."}, {"customer": "Wendy Zhao", "rating": 4, "body": "Chilling. The appendix on Newspeak is underrated."}], "tags": ["dystopia", "surveillance", "totalitarian", "political", "thought-police"]}'

put_doc "book:animal-farm" '{"type": "book", "title": "Animal Farm", "isbn": "978-0451526342", "genre": "Fiction", "price": 7.99, "published_date": "1945-08-17", "in_stock": true, "authors": [{"name": "George Orwell", "born_year": 1903}], "reviews": [{"customer": "Frank Okafor", "rating": 5, "body": "A perfect allegory. Every line carries weight."}, {"customer": "Liam O'\''Brien", "rating": 4, "body": "Short but devastating. Should be required reading."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Gets the point across but it'\''s pretty heavy-handed."}], "tags": ["allegory", "revolution", "communism", "satire", "animals"]}'

put_doc "book:pride-and-prejudice" '{"type": "book", "title": "Pride and Prejudice", "isbn": "978-0141439518", "genre": "Romance", "price": 6.99, "published_date": "1813-01-28", "in_stock": true, "authors": [{"name": "Jane Austen", "born_year": 1775}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "The original enemies-to-lovers. Austen is timeless."}, {"customer": "Iris Novak", "rating": 5, "body": "Witty, sharp, and romantic. Darcy forever."}, {"customer": "Maya Patel", "rating": 4, "body": "Austen'\''s social commentary is razor-sharp beneath the romance."}, {"customer": "Tyler Brooks", "rating": 2, "body": "Rich people have polite conversations for 300 pages. Not for me."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Well-crafted but the class obsession feels exhausting."}], "tags": ["regency", "marriage", "class", "manners", "wit"]}'

put_doc "book:sense-and-sensibility" '{"type": "book", "title": "Sense and Sensibility", "isbn": "978-0141439662", "genre": "Romance", "price": 6.99, "published_date": "1811-10-30", "in_stock": true, "authors": [{"name": "Jane Austen", "born_year": 1775}], "reviews": [{"customer": "Priya Sharma", "rating": 3, "body": "Fine but not as sharp as Pride and Prejudice."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Elinor'\''s quiet strength makes this underrated Austen."}], "tags": ["sisters", "romance", "regency", "restraint", "emotion"]}'

put_doc "book:emma" '{"type": "book", "title": "Emma", "isbn": "978-0141439587", "genre": "Romance", "price": 7.49, "published_date": "1815-12-23", "in_stock": true, "authors": [{"name": "Jane Austen", "born_year": 1775}], "reviews": [{"customer": "Iris Novak", "rating": 3, "body": "Charming but the matchmaking premise wears thin."}, {"customer": "Sofia Andersson", "rating": 4, "body": "Emma is infuriating and lovable in equal measure."}], "tags": ["matchmaking", "comedy", "class", "village", "romance"]}'

put_doc "book:do-androids-dream-of-electric-sheep" '{"type": "book", "title": "Do Androids Dream of Electric Sheep?", "isbn": "978-0345404473", "genre": "Science Fiction", "price": 10.99, "published_date": "1968-01-01", "in_stock": true, "authors": [{"name": "Philip K. Dick", "born_year": 1928}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "Mind-bending questions about what makes us human."}, {"customer": "Keiko Tanaka", "rating": 4, "body": "PKD at his philosophical best. Better than the movie."}, {"customer": "Rashid Kouri", "rating": 3, "body": "The ideas are great but the writing feels rushed."}, {"customer": "Yuki Mori", "rating": 3, "body": "Interesting thought experiment. Execution is uneven."}], "tags": ["android", "empathy", "dystopia", "identity", "bounty-hunter"]}'

put_doc "book:a-scanner-darkly" '{"type": "book", "title": "A Scanner Darkly", "isbn": "978-0547572178", "genre": "Science Fiction", "price": 11.49, "published_date": "1977-01-01", "in_stock": true, "authors": [{"name": "Philip K. Dick", "born_year": 1928}], "reviews": [{"customer": "Viktor Petrov", "rating": 2, "body": "Paranoid and confusing. I could never follow what was real."}, {"customer": "Quinn Murphy", "rating": 4, "body": "A drug-fueled nightmare that somehow makes perfect sense."}], "tags": ["drugs", "surveillance", "identity", "paranoia", "undercover"]}'

put_doc "book:the-man-in-the-high-castle" '{"type": "book", "title": "The Man in the High Castle", "isbn": "978-0547572482", "genre": "Science Fiction", "price": 10.99, "published_date": "1962-01-01", "in_stock": true, "authors": [{"name": "Philip K. Dick", "born_year": 1928}], "reviews": [{"customer": "Jamal Washington", "rating": 3, "body": "Interesting alternate history premise but the pace is very slow."}, {"customer": "Wendy Zhao", "rating": 4, "body": "PKD'\''s best world-building. The I Ching framing is fascinating."}], "tags": ["alternate-history", "wwii", "axis", "resistance", "reality"]}'

put_doc "book:the-shining" '{"type": "book", "title": "The Shining", "isbn": "978-0307743657", "genre": "Horror", "price": 9.99, "published_date": "1977-01-28", "in_stock": true, "authors": [{"name": "Stephen King", "born_year": 1947}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "The most terrifying haunted house story ever written."}, {"customer": "Frank Okafor", "rating": 4, "body": "King builds dread like no one else. Claustrophobic brilliance."}, {"customer": "Olivia Santos", "rating": 5, "body": "All work and no play... This book genuinely scared me."}, {"customer": "Uma Okonkwo", "rating": 3, "body": "Effective horror, but King over-explains the supernatural elements."}], "tags": ["hotel", "isolation", "madness", "ghosts", "winter"]}'

put_doc "book:it" '{"type": "book", "title": "It", "isbn": "978-1501142970", "genre": "Horror", "price": 12.99, "published_date": "1986-09-15", "in_stock": true, "authors": [{"name": "Stephen King", "born_year": 1947}], "reviews": [{"customer": "Hassan Ali", "rating": 4, "body": "Massive and sprawling, but the Losers Club keeps you invested."}, {"customer": "Noah Fischer", "rating": 5, "body": "King'\''s magnum opus. Friendship vs. cosmic evil at its best."}, {"customer": "Tyler Brooks", "rating": 2, "body": "Way too long. Should have been half the length. Needed an editor."}, {"customer": "Yuki Mori", "rating": 3, "body": "Great premise, but it drags in the adult timeline sections."}], "tags": ["clown", "childhood", "fear", "friendship", "evil"]}'

put_doc "book:the-stand" '{"type": "book", "title": "The Stand", "isbn": "978-0307743688", "genre": "Horror", "price": 11.99, "published_date": "1978-10-03", "in_stock": true, "authors": [{"name": "Stephen King", "born_year": 1947}], "reviews": [{"customer": "Jamal Washington", "rating": 4, "body": "Epic post-apocalyptic good vs. evil. Peak King."}, {"customer": "Priya Sharma", "rating": 3, "body": "The first half is incredible. The second half loses its way."}, {"customer": "Viktor Petrov", "rating": 1, "body": "1400 pages for a story that goes nowhere satisfying. Gave up."}], "tags": ["plague", "apocalypse", "good-vs-evil", "survival", "epic"]}'

put_doc "book:misery" '{"type": "book", "title": "Misery", "isbn": "978-1501143106", "genre": "Horror", "price": 9.49, "published_date": "1987-06-08", "in_stock": true, "authors": [{"name": "Stephen King", "born_year": 1947}], "reviews": [{"customer": "Quinn Murphy", "rating": 5, "body": "The most psychologically intense King novel. Annie Wilkes is iconic."}, {"customer": "Xavier Dubois", "rating": 4, "body": "Lean and mean. King at his most focused."}], "tags": ["captivity", "obsession", "writer", "fan", "psychological"]}'

put_doc "book:2001-a-space-odyssey" '{"type": "book", "title": "2001: A Space Odyssey", "isbn": "978-0451457998", "genre": "Science Fiction", "price": 8.99, "published_date": "1968-07-01", "in_stock": true, "authors": [{"name": "Arthur C. Clarke", "born_year": 1917}], "reviews": [{"customer": "Carol Williams", "rating": 5, "body": "Visionary. Clarke imagined the future better than anyone."}, {"customer": "Noah Fischer", "rating": 5, "body": "The monolith scenes are among the best in all of sci-fi."}, {"customer": "Sofia Andersson", "rating": 3, "body": "More of a philosophical treatise than a novel. Cold and distant."}], "tags": ["space", "AI", "evolution", "monolith", "jupiter"]}'

put_doc "book:rendezvous-with-rama" '{"type": "book", "title": "Rendezvous with Rama", "isbn": "978-0358380221", "genre": "Science Fiction", "price": 10.49, "published_date": "1973-06-01", "in_stock": true, "authors": [{"name": "Arthur C. Clarke", "born_year": 1917}], "reviews": [{"customer": "Hassan Ali", "rating": 4, "body": "Hard sci-fi exploration done right. Rama is unforgettable."}, {"customer": "Yuki Mori", "rating": 3, "body": "Fascinating setting but the characters are forgettable."}], "tags": ["alien", "exploration", "hard-sci-fi", "mystery", "spacecraft"]}'

put_doc "book:childhoods-end" '{"type": "book", "title": "Childhood'\''s End", "isbn": "978-0345444059", "genre": "Science Fiction", "price": 9.49, "published_date": "1953-01-01", "in_stock": true, "authors": [{"name": "Arthur C. Clarke", "born_year": 1917}], "reviews": [{"customer": "Elena Rodriguez", "rating": 4, "body": "Clarke'\''s most haunting ending. The Overlords are terrifying."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Started strong but the final act is too abstract for me."}], "tags": ["aliens", "utopia", "evolution", "overlords", "transcendence"]}'

put_doc "book:the-handmaids-tale" '{"type": "book", "title": "The Handmaid'\''s Tale", "isbn": "978-0385490818", "genre": "Fiction", "price": 10.99, "published_date": "1985-01-01", "in_stock": true, "authors": [{"name": "Margaret Atwood", "born_year": 1939}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "A chilling and necessary dystopia. Atwood is a prophet."}, {"customer": "Iris Novak", "rating": 5, "body": "Terrifying because it all feels possible. Essential reading."}, {"customer": "Maya Patel", "rating": 4, "body": "Powerful and disturbing. The TV show doesn'\''t capture half of it."}, {"customer": "Tyler Brooks", "rating": 3, "body": "Well-written but relentlessly bleak. Had to take breaks."}, {"customer": "Wendy Zhao", "rating": 4, "body": "The restraint of the prose makes it even more devastating."}], "tags": ["dystopia", "feminism", "theocracy", "resistance", "oppression"]}'

put_doc "book:oryx-and-crake" '{"type": "book", "title": "Oryx and Crake", "isbn": "978-0385721677", "genre": "Science Fiction", "price": 11.99, "published_date": "2003-05-01", "in_stock": true, "authors": [{"name": "Margaret Atwood", "born_year": 1939}], "reviews": [{"customer": "Priya Sharma", "rating": 4, "body": "Bleak, inventive, and very Atwood. The biotech is disturbingly plausible."}, {"customer": "Uma Okonkwo", "rating": 3, "body": "Clever but hard to care about any of the characters."}], "tags": ["biotech", "apocalypse", "genetic-engineering", "corporate", "dystopia"]}'

put_doc "book:slaughterhouse-five" '{"type": "book", "title": "Slaughterhouse-Five", "isbn": "978-0385333481", "genre": "Fiction", "price": 9.99, "published_date": "1969-03-31", "in_stock": true, "authors": [{"name": "Kurt Vonnegut", "born_year": 1922}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "Vonnegut'\''s masterpiece. So it goes."}, {"customer": "Liam O'\''Brien", "rating": 5, "body": "Anti-war fiction at its most inventive and heartbreaking."}, {"customer": "Quinn Murphy", "rating": 3, "body": "I get why people love it, but the structure felt gimmicky to me."}, {"customer": "Viktor Petrov", "rating": 2, "body": "Disjointed and pretentious. The time-travel adds nothing."}], "tags": ["war", "time-travel", "absurdism", "dresden", "aliens"]}'

put_doc "book:cats-cradle" '{"type": "book", "title": "Cat'\''s Cradle", "isbn": "978-0812993543", "genre": "Fiction", "price": 8.99, "published_date": "1963-01-01", "in_stock": true, "authors": [{"name": "Kurt Vonnegut", "born_year": 1922}], "reviews": [{"customer": "Rashid Kouri", "rating": 4, "body": "Ice-nine is the scariest fictional invention I'\''ve encountered."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Satirical but a bit scattered compared to Slaughterhouse-Five."}], "tags": ["satire", "science", "religion", "apocalypse", "ice-nine"]}'

put_doc "book:fahrenheit-451" '{"type": "book", "title": "Fahrenheit 451", "isbn": "978-1451673319", "genre": "Fiction", "price": 8.99, "published_date": "1953-10-19", "in_stock": true, "authors": [{"name": "Ray Bradbury", "born_year": 1920}], "reviews": [{"customer": "Hassan Ali", "rating": 5, "body": "A love letter to books. Bradbury writes fire beautifully."}, {"customer": "Olivia Santos", "rating": 4, "body": "More relevant now than when it was written."}, {"customer": "Sofia Andersson", "rating": 3, "body": "Great concept but Bradbury'\''s prose is too flowery for the subject."}, {"customer": "Yuki Mori", "rating": 4, "body": "Short, sharp, and urgent. The fire imagery is stunning."}], "tags": ["censorship", "books", "firemen", "dystopia", "knowledge"]}'

put_doc "book:the-martian-chronicles" '{"type": "book", "title": "The Martian Chronicles", "isbn": "978-1451678192", "genre": "Science Fiction", "price": 9.49, "published_date": "1950-05-01", "in_stock": true, "authors": [{"name": "Ray Bradbury", "born_year": 1920}], "reviews": [{"customer": "Frank Okafor", "rating": 3, "body": "Uneven. Some stories are brilliant, others feel like filler."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Bradbury'\''s Mars is more about loneliness than science. Beautiful."}], "tags": ["mars", "colonization", "nostalgia", "alien", "humanity"]}'

put_doc "book:something-wicked-this-way-comes" '{"type": "book", "title": "Something Wicked This Way Comes", "isbn": "978-1501167713", "genre": "Horror", "price": 10.49, "published_date": "1962-09-01", "in_stock": true, "authors": [{"name": "Ray Bradbury", "born_year": 1920}], "reviews": [{"customer": "Quinn Murphy", "rating": 4, "body": "Carnival horror at its best. Mr. Dark is genuinely unsettling."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Atmospheric but the prose gets in its own way."}], "tags": ["carnival", "evil", "youth", "temptation", "autumn"]}'

put_doc "book:crime-and-punishment" '{"type": "book", "title": "Crime and Punishment", "isbn": "978-0486415871", "genre": "Fiction", "price": 7.99, "published_date": "1866-01-01", "in_stock": true, "authors": [{"name": "Fyodor Dostoevsky", "born_year": 1821}], "reviews": [{"customer": "Grace Kim", "rating": 5, "body": "Dostoevsky reaches into your soul and doesn'\''t let go."}, {"customer": "Keiko Tanaka", "rating": 4, "body": "The psychological depth is staggering. Heavy but rewarding."}, {"customer": "Priya Sharma", "rating": 3, "body": "Brilliant but punishing to read. Not exactly a page-turner."}, {"customer": "Viktor Petrov", "rating": 2, "body": "Pretentious and depressing. Life is too short for this."}], "tags": ["guilt", "murder", "redemption", "philosophy", "poverty"]}'

put_doc "book:the-brothers-karamazov" '{"type": "book", "title": "The Brothers Karamazov", "isbn": "978-0374528379", "genre": "Fiction", "price": 12.99, "published_date": "1880-11-01", "in_stock": true, "authors": [{"name": "Fyodor Dostoevsky", "born_year": 1821}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "The Grand Inquisitor chapter alone is worth the price of admission."}, {"customer": "Rashid Kouri", "rating": 4, "body": "Massive and demanding but deeply rewarding if you stick with it."}, {"customer": "Yuki Mori", "rating": 2, "body": "Could not keep the characters straight. Gave up at page 200."}], "tags": ["family", "faith", "murder", "philosophy", "russia"]}'

put_doc "book:notes-from-underground" '{"type": "book", "title": "Notes from Underground", "isbn": "978-0679734529", "genre": "Fiction", "price": 6.99, "published_date": "1864-01-01", "in_stock": true, "authors": [{"name": "Fyodor Dostoevsky", "born_year": 1821}], "reviews": [{"customer": "Liam O'\''Brien", "rating": 4, "body": "The original unreliable narrator rant. Surprisingly modern."}, {"customer": "Tyler Brooks", "rating": 3, "body": "I get it, he'\''s miserable. Did it need to be this repetitive?"}], "tags": ["existentialism", "isolation", "philosophy", "spite", "confession"]}'

put_doc "book:one-hundred-years-of-solitude" '{"type": "book", "title": "One Hundred Years of Solitude", "isbn": "978-0060883287", "genre": "Fiction", "price": 11.99, "published_date": "1967-05-30", "in_stock": true, "authors": [{"name": "Gabriel Garcia Marquez", "born_year": 1927}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "Magical realism at its absolute peak. A generational saga."}, {"customer": "Frank Okafor", "rating": 5, "body": "Marquez makes the impossible feel inevitable."}, {"customer": "Iris Novak", "rating": 4, "body": "Keeping track of the names is a challenge, but worth it."}, {"customer": "Sofia Andersson", "rating": 2, "body": "Everyone has the same name. I was lost by page 50."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Beautiful sentences but the circular structure is frustrating."}], "tags": ["magical-realism", "family", "latin-america", "time", "solitude"]}'

put_doc "book:love-in-the-time-of-cholera" '{"type": "book", "title": "Love in the Time of Cholera", "isbn": "978-0307389732", "genre": "Romance", "price": 10.99, "published_date": "1985-01-01", "in_stock": true, "authors": [{"name": "Gabriel Garcia Marquez", "born_year": 1927}], "reviews": [{"customer": "Iris Novak", "rating": 4, "body": "A love story spanning decades. Patient and beautiful."}, {"customer": "Uma Okonkwo", "rating": 3, "body": "Romantic but Florentino is honestly kind of creepy."}, {"customer": "Priya Sharma", "rating": 2, "body": "The obsession isn'\''t romantic, it'\''s stalking. Couldn'\''t root for him."}], "tags": ["love", "aging", "obsession", "patience", "river"]}'

put_doc "book:beloved" '{"type": "book", "title": "Beloved", "isbn": "978-1400033416", "genre": "Fiction", "price": 11.99, "published_date": "1987-09-02", "in_stock": true, "authors": [{"name": "Toni Morrison", "born_year": 1931}], "reviews": [{"customer": "Jamal Washington", "rating": 5, "body": "Morrison'\''s prose is devastating. This book changes you."}, {"customer": "Maya Patel", "rating": 5, "body": "The most powerful novel I'\''ve ever read about memory and trauma."}, {"customer": "Viktor Petrov", "rating": 3, "body": "Important and well-written but extremely difficult to get through."}], "tags": ["slavery", "memory", "ghost", "trauma", "motherhood"]}'

put_doc "book:song-of-solomon" '{"type": "book", "title": "Song of Solomon", "isbn": "978-1400033423", "genre": "Fiction", "price": 10.99, "published_date": "1977-01-01", "in_stock": true, "authors": [{"name": "Toni Morrison", "born_year": 1931}], "reviews": [{"customer": "Uma Okonkwo", "rating": 4, "body": "Morrison'\''s prose sings. A journey through identity and heritage."}, {"customer": "Yuki Mori", "rating": 3, "body": "Lyrical but I found the plot hard to follow at times."}], "tags": ["identity", "family", "flight", "heritage", "names"]}'

put_doc "book:norwegian-wood" '{"type": "book", "title": "Norwegian Wood", "isbn": "978-0375704024", "genre": "Fiction", "price": 10.99, "published_date": "1987-09-04", "in_stock": true, "authors": [{"name": "Haruki Murakami", "born_year": 1949}], "reviews": [{"customer": "Keiko Tanaka", "rating": 4, "body": "Murakami captures the ache of youth and loss perfectly."}, {"customer": "Olivia Santos", "rating": 5, "body": "Quiet, melancholy, and beautiful. My favorite Murakami."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Atmospheric but all the characters feel emotionally numb."}, {"customer": "Rashid Kouri", "rating": 2, "body": "Murakami'\''s male protagonists are all the same passive sad guy."}], "tags": ["loss", "love", "nostalgia", "youth", "tokyo"]}'

put_doc "book:kafka-on-the-shore" '{"type": "book", "title": "Kafka on the Shore", "isbn": "978-1400079278", "genre": "Fiction", "price": 11.49, "published_date": "2002-09-12", "in_stock": true, "authors": [{"name": "Haruki Murakami", "born_year": 1949}], "reviews": [{"customer": "Grace Kim", "rating": 4, "body": "Surreal and dreamlike. Not everything makes sense, and that'\''s the point."}, {"customer": "Tyler Brooks", "rating": 3, "body": "Interesting imagery but I had no idea what was going on half the time."}], "tags": ["surreal", "cats", "parallel", "metaphysics", "journey"]}'

put_doc "book:1q84" '{"type": "book", "title": "1Q84", "isbn": "978-0307476463", "genre": "Fiction", "price": 14.99, "published_date": "2009-05-29", "in_stock": true, "authors": [{"name": "Haruki Murakami", "born_year": 1949}], "reviews": [{"customer": "Keiko Tanaka", "rating": 3, "body": "Ambitious but at 1000+ pages, it needed tighter editing."}, {"customer": "Yuki Mori", "rating": 2, "body": "The parallel worlds concept is wasted on a bloated love story."}], "tags": ["parallel-worlds", "cult", "love", "mystery", "tokyo"]}'

put_doc "book:kindred" '{"type": "book", "title": "Kindred", "isbn": "978-0807083697", "genre": "Science Fiction", "price": 10.99, "published_date": "1979-06-01", "in_stock": true, "authors": [{"name": "Octavia Butler", "born_year": 1947}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "Butler makes time travel personal and political. Unforgettable."}, {"customer": "Uma Okonkwo", "rating": 5, "body": "Visceral and harrowing. One of the most important sci-fi novels."}, {"customer": "Priya Sharma", "rating": 4, "body": "Uncomfortable in all the right ways. Butler pulls no punches."}], "tags": ["time-travel", "slavery", "survival", "race", "history"]}'

put_doc "book:parable-of-the-sower" '{"type": "book", "title": "Parable of the Sower", "isbn": "978-1538732182", "genre": "Science Fiction", "price": 11.49, "published_date": "1993-01-01", "in_stock": true, "authors": [{"name": "Octavia Butler", "born_year": 1947}], "reviews": [{"customer": "Maya Patel", "rating": 4, "body": "Prescient dystopia. Butler saw our climate future decades ago."}, {"customer": "Wendy Zhao", "rating": 3, "body": "The world-building is strong but the diary format gets repetitive."}], "tags": ["dystopia", "religion", "survival", "climate", "community"]}'

put_doc "book:the-hitchhikers-guide-to-the-galaxy" '{"type": "book", "title": "The Hitchhiker'\''s Guide to the Galaxy", "isbn": "978-0345391803", "genre": "Science Fiction", "price": 8.99, "published_date": "1979-10-12", "in_stock": true, "authors": [{"name": "Douglas Adams", "born_year": 1952}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "Don'\''t panic! The funniest sci-fi book ever written. Period."}, {"customer": "Dan Chen", "rating": 5, "body": "42. That'\''s all you need to know. Read it."}, {"customer": "Liam O'\''Brien", "rating": 4, "body": "British humor in space. Douglas Adams was a genius."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Amusing but the plot is basically random events strung together."}, {"customer": "Viktor Petrov", "rating": 1, "body": "Tried three times. Can'\''t stand the humor. Deeply unfunny to me."}], "tags": ["humor", "space", "earth", "absurdism", "towel", "42"]}'

put_doc "book:the-restaurant-at-the-end-of-the-universe" '{"type": "book", "title": "The Restaurant at the End of the Universe", "isbn": "978-0345391810", "genre": "Science Fiction", "price": 8.99, "published_date": "1980-10-01", "in_stock": true, "authors": [{"name": "Douglas Adams", "born_year": 1952}], "reviews": [{"customer": "Liam O'\''Brien", "rating": 3, "body": "Diminishing returns. The first book was much funnier."}, {"customer": "Xavier Dubois", "rating": 4, "body": "Milliways is one of the best set pieces in all of comedy sci-fi."}], "tags": ["humor", "space", "time-travel", "restaurant", "absurdism"]}'

put_doc "book:frankenstein" '{"type": "book", "title": "Frankenstein", "isbn": "978-0486282114", "genre": "Horror", "price": 6.99, "published_date": "1818-01-01", "in_stock": true, "authors": [{"name": "Mary Shelley", "born_year": 1797}], "reviews": [{"customer": "Frank Okafor", "rating": 4, "body": "The original. Shelley invented science fiction at 18 years old."}, {"customer": "Iris Novak", "rating": 5, "body": "Far more philosophical than most people expect. A gothic treasure."}, {"customer": "Tyler Brooks", "rating": 3, "body": "Historically important but the framing device is clunky."}, {"customer": "Yuki Mori", "rating": 3, "body": "The monster is sympathetic, Victor is insufferable. Maybe that'\''s the point."}], "tags": ["monster", "creation", "science", "hubris", "gothic"]}'

put_doc "book:at-the-mountains-of-madness" '{"type": "book", "title": "At the Mountains of Madness", "isbn": "978-0812974416", "genre": "Horror", "price": 8.99, "published_date": "1936-02-01", "in_stock": true, "authors": [{"name": "H.P. Lovecraft", "born_year": 1890}], "reviews": [{"customer": "Quinn Murphy", "rating": 4, "body": "Lovecraft'\''s best long-form work. The dread is palpable."}, {"customer": "Viktor Petrov", "rating": 3, "body": "Great atmosphere but Lovecraft'\''s prose is exhaustingly purple."}, {"customer": "Hassan Ali", "rating": 2, "body": "Can'\''t separate the cosmic horror from the author'\''s real-world bigotry."}], "tags": ["antarctic", "lovecraft", "elder-things", "cosmic-horror", "expedition"]}'

put_doc "book:the-call-of-cthulhu" '{"type": "book", "title": "The Call of Cthulhu", "isbn": "978-1689177832", "genre": "Horror", "price": 5.99, "published_date": "1928-02-01", "in_stock": true, "authors": [{"name": "H.P. Lovecraft", "born_year": 1890}], "reviews": [{"customer": "Frank Okafor", "rating": 3, "body": "The mythos is iconic but the actual story is paper-thin."}, {"customer": "Wendy Zhao", "rating": 4, "body": "Short and effective. Ph'\''nglui mglw'\''nafh Cthulhu."}], "tags": ["cthulhu", "cosmic-horror", "cult", "ocean", "madness"]}'

put_doc "book:brave-new-world" '{"type": "book", "title": "Brave New World", "isbn": "978-0060850524", "genre": "Fiction", "price": 9.99, "published_date": "1932-01-01", "in_stock": true, "authors": [{"name": "Aldous Huxley", "born_year": 1894}], "reviews": [{"customer": "Carol Williams", "rating": 4, "body": "Huxley'\''s dystopia is the one we actually got. Soma for everyone."}, {"customer": "Hassan Ali", "rating": 5, "body": "More relevant than 1984 in the age of distraction."}, {"customer": "Priya Sharma", "rating": 3, "body": "Interesting ideas but the characters are deliberately one-dimensional."}, {"customer": "Xavier Dubois", "rating": 2, "body": "Feels like a thought experiment, not a novel. No emotional core."}], "tags": ["dystopia", "consumerism", "conditioning", "pleasure", "control"]}'

put_doc "book:blood-meridian" '{"type": "book", "title": "Blood Meridian", "isbn": "978-0679728757", "genre": "Fiction", "price": 11.99, "published_date": "1985-04-01", "in_stock": true, "authors": [{"name": "Cormac McCarthy", "born_year": 1933}], "reviews": [{"customer": "Jamal Washington", "rating": 5, "body": "The most violent novel I'\''ve ever read, and somehow the most beautiful."}, {"customer": "Quinn Murphy", "rating": 4, "body": "McCarthy writes violence like poetry. The Judge is unforgettable."}, {"customer": "Viktor Petrov", "rating": 1, "body": "Gratuitous violence disguised as literature. Absolutely hated it."}, {"customer": "Sofia Andersson", "rating": 3, "body": "Beautifully written but I felt physically ill reading parts of it."}], "tags": ["western", "violence", "philosophy", "desert", "war"]}'

put_doc "book:the-road" '{"type": "book", "title": "The Road", "isbn": "978-0307387899", "genre": "Fiction", "price": 10.99, "published_date": "2006-09-26", "in_stock": true, "authors": [{"name": "Cormac McCarthy", "born_year": 1933}], "reviews": [{"customer": "Jamal Washington", "rating": 5, "body": "Devastatingly spare and beautiful. McCarthy'\''s finest work."}, {"customer": "Noah Fischer", "rating": 5, "body": "I read it in one sitting and cried at the end."}, {"customer": "Rashid Kouri", "rating": 4, "body": "Bleak but the father-son bond carries you through the darkness."}, {"customer": "Yuki Mori", "rating": 3, "body": "Relentlessly grim. Well-written but I felt drained afterward."}], "tags": ["post-apocalyptic", "father-son", "survival", "hope", "ash"]}'

put_doc "book:no-country-for-old-men" '{"type": "book", "title": "No Country for Old Men", "isbn": "978-0375706677", "genre": "Thriller", "price": 10.49, "published_date": "2005-07-19", "in_stock": true, "authors": [{"name": "Cormac McCarthy", "born_year": 1933}], "reviews": [{"customer": "Quinn Murphy", "rating": 4, "body": "Taut and terrifying. Chigurh is one of fiction'\''s great villains."}, {"customer": "Xavier Dubois", "rating": 5, "body": "McCarthy'\''s most accessible novel. The coin toss scene is perfection."}], "tags": ["crime", "fate", "violence", "texas", "cat-and-mouse"]}'

put_doc "book:ficciones" '{"type": "book", "title": "Ficciones", "isbn": "978-0802130303", "genre": "Fiction", "price": 9.99, "published_date": "1944-01-01", "in_stock": true, "authors": [{"name": "Jorge Luis Borges", "born_year": 1899}], "reviews": [{"customer": "Grace Kim", "rating": 5, "body": "Borges builds infinite worlds in five pages. Astonishing."}, {"customer": "Rashid Kouri", "rating": 4, "body": "Mind-bending. Every story is a puzzle box."}, {"customer": "Tyler Brooks", "rating": 2, "body": "Intellectual show-off writing. I felt stupid, not enlightened."}], "tags": ["labyrinths", "philosophy", "metafiction", "infinity", "puzzles"]}'

put_doc "book:things-fall-apart" '{"type": "book", "title": "Things Fall Apart", "isbn": "978-0385474542", "genre": "Fiction", "price": 8.99, "published_date": "1958-01-01", "in_stock": true, "authors": [{"name": "Chinua Achebe", "born_year": 1930}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "A shattering novel about colonialism and cultural destruction."}, {"customer": "Frank Okafor", "rating": 4, "body": "Achebe writes with clarity and power. Essential African literature."}, {"customer": "Uma Okonkwo", "rating": 5, "body": "Should be required reading everywhere. Okonkwo is unforgettable."}, {"customer": "Yuki Mori", "rating": 3, "body": "Important but the narrative distance kept me from connecting."}], "tags": ["colonialism", "igbo", "tradition", "change", "africa"]}'

put_doc "book:mrs-dalloway" '{"type": "book", "title": "Mrs Dalloway", "isbn": "978-0156628709", "genre": "Fiction", "price": 8.49, "published_date": "1925-05-14", "in_stock": true, "authors": [{"name": "Virginia Woolf", "born_year": 1882}], "reviews": [{"customer": "Priya Sharma", "rating": 4, "body": "Woolf'\''s stream of consciousness is breathtaking when it clicks."}, {"customer": "Viktor Petrov", "rating": 1, "body": "Nothing happens. Literally nothing. A woman plans a party."}, {"customer": "Sofia Andersson", "rating": 3, "body": "Beautifully written but I kept losing the thread of who was thinking."}], "tags": ["stream-of-consciousness", "london", "party", "memory", "time"]}'

put_doc "book:to-the-lighthouse" '{"type": "book", "title": "To the Lighthouse", "isbn": "978-0156907392", "genre": "Fiction", "price": 9.49, "published_date": "1927-05-05", "in_stock": true, "authors": [{"name": "Virginia Woolf", "born_year": 1882}], "reviews": [{"customer": "Grace Kim", "rating": 4, "body": "Woolf captures the passage of time like no other writer."}, {"customer": "Wendy Zhao", "rating": 3, "body": "The Time Passes section is stunning. The rest is harder to love."}], "tags": ["memory", "time", "family", "art", "perception"]}'

put_doc "book:the-old-man-and-the-sea" '{"type": "book", "title": "The Old Man and the Sea", "isbn": "978-0684801223", "genre": "Fiction", "price": 7.99, "published_date": "1952-09-01", "in_stock": true, "authors": [{"name": "Ernest Hemingway", "born_year": 1899}], "reviews": [{"customer": "Carol Williams", "rating": 4, "body": "Hemingway stripped to the bone. Simple but profound."}, {"customer": "Olivia Santos", "rating": 5, "body": "Man vs. nature, man vs. self. A perfect novella."}, {"customer": "Tyler Brooks", "rating": 3, "body": "I respect the craft but honestly found it boring."}, {"customer": "Rashid Kouri", "rating": 2, "body": "Old man catches fish. Old man loses fish. That'\''s it. That'\''s the book."}], "tags": ["sea", "fishing", "endurance", "cuba", "aging"]}'

put_doc "book:a-farewell-to-arms" '{"type": "book", "title": "A Farewell to Arms", "isbn": "978-0684801469", "genre": "Fiction", "price": 9.99, "published_date": "1929-09-27", "in_stock": true, "authors": [{"name": "Ernest Hemingway", "born_year": 1899}], "reviews": [{"customer": "Noah Fischer", "rating": 4, "body": "Hemingway'\''s war writing is raw and honest."}, {"customer": "Xavier Dubois", "rating": 3, "body": "The love story feels forced compared to the war scenes."}], "tags": ["war", "love", "italy", "wwi", "loss"]}'

put_doc "book:for-whom-the-bell-tolls" '{"type": "book", "title": "For Whom the Bell Tolls", "isbn": "978-0684803357", "genre": "Fiction", "price": 10.99, "published_date": "1940-10-21", "in_stock": true, "authors": [{"name": "Ernest Hemingway", "born_year": 1899}], "reviews": [{"customer": "Frank Okafor", "rating": 4, "body": "Hemingway in Spain. The guerrilla camp scenes are vivid."}, {"customer": "Uma Okonkwo", "rating": 3, "body": "Good but not his best. The Spanish dialogue translations are awkward."}], "tags": ["spanish-civil-war", "guerrilla", "love", "duty", "sacrifice"]}'

put_doc "book:the-trial" '{"type": "book", "title": "The Trial", "isbn": "978-0805209990", "genre": "Fiction", "price": 8.99, "published_date": "1925-04-26", "in_stock": true, "authors": [{"name": "Franz Kafka", "born_year": 1883}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "Kafka captures the nightmare of bureaucracy like no one else."}, {"customer": "Liam O'\''Brien", "rating": 4, "body": "Absurd, unsettling, and somehow very funny."}, {"customer": "Tyler Brooks", "rating": 3, "body": "I get the allegory but it'\''s frustrating by design."}], "tags": ["bureaucracy", "absurdism", "guilt", "law", "existential"]}'

put_doc "book:the-metamorphosis" '{"type": "book", "title": "The Metamorphosis", "isbn": "978-0553213690", "genre": "Fiction", "price": 5.99, "published_date": "1915-01-01", "in_stock": true, "authors": [{"name": "Franz Kafka", "born_year": 1883}], "reviews": [{"customer": "Keiko Tanaka", "rating": 5, "body": "The most famous opening line in literature. Devastating."}, {"customer": "Quinn Murphy", "rating": 4, "body": "Short and devastating. Kafka'\''s alienation has never felt so literal."}, {"customer": "Yuki Mori", "rating": 3, "body": "Weird and sad. The family'\''s reaction is the real horror."}], "tags": ["transformation", "alienation", "family", "insect", "existential"]}'

put_doc "book:neuromancer" '{"type": "book", "title": "Neuromancer", "isbn": "978-0441569595", "genre": "Science Fiction", "price": 10.99, "published_date": "1984-07-01", "in_stock": true, "authors": [{"name": "William Gibson", "born_year": 1948}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "The book that launched cyberpunk. Still feels ahead of its time."}, {"customer": "Hassan Ali", "rating": 4, "body": "Gibson'\''s prose is electric. Dense but worth the effort."}, {"customer": "Priya Sharma", "rating": 3, "body": "Cool style but I had no idea what was happening for the first 100 pages."}, {"customer": "Wendy Zhao", "rating": 2, "body": "All vibes, no substance. Style over everything."}], "tags": ["cyberpunk", "hacking", "AI", "cyberspace", "noir"]}'

put_doc "book:count-zero" '{"type": "book", "title": "Count Zero", "isbn": "978-0441117734", "genre": "Science Fiction", "price": 10.49, "published_date": "1986-03-01", "in_stock": true, "authors": [{"name": "William Gibson", "born_year": 1948}], "reviews": [{"customer": "Rashid Kouri", "rating": 3, "body": "More accessible than Neuromancer but less groundbreaking."}], "tags": ["cyberpunk", "voodoo", "AI", "art", "corporate"]}'

put_doc "book:the-fifth-season" '{"type": "book", "title": "The Fifth Season", "isbn": "978-0316229296", "genre": "Fantasy", "price": 11.99, "published_date": "2015-08-04", "in_stock": true, "authors": [{"name": "N.K. Jemisin", "born_year": 1972}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "Jemisin reinvented fantasy. The second-person narration is genius."}, {"customer": "Maya Patel", "rating": 5, "body": "Three consecutive Hugos and every one of them deserved."}, {"customer": "Sofia Andersson", "rating": 4, "body": "Bold and original. The world-building is unlike anything else."}, {"customer": "Viktor Petrov", "rating": 2, "body": "Second person narration is exhausting. Couldn'\''t get past chapter 3."}], "tags": ["apocalypse", "oppression", "seismic", "identity", "survival"]}'

put_doc "book:the-obelisk-gate" '{"type": "book", "title": "The Obelisk Gate", "isbn": "978-0316229265", "genre": "Fantasy", "price": 11.99, "published_date": "2016-08-16", "in_stock": true, "authors": [{"name": "N.K. Jemisin", "born_year": 1972}], "reviews": [{"customer": "Elena Rodriguez", "rating": 4, "body": "Strong middle book. Nassun'\''s chapters are heartbreaking."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Good but suffers from middle-book syndrome."}], "tags": ["apocalypse", "community", "power", "survival", "obelisks"]}'

put_doc "book:the-stone-sky" '{"type": "book", "title": "The Stone Sky", "isbn": "978-0316229241", "genre": "Fantasy", "price": 11.99, "published_date": "2017-08-15", "in_stock": true, "authors": [{"name": "N.K. Jemisin", "born_year": 1972}], "reviews": [{"customer": "Maya Patel", "rating": 5, "body": "A perfect conclusion. Jemisin sticks the landing beautifully."}, {"customer": "Sofia Andersson", "rating": 4, "body": "The trilogy as a whole is a landmark achievement."}], "tags": ["apocalypse", "moon", "resolution", "power", "motherhood"]}'

put_doc "book:the-three-body-problem" '{"type": "book", "title": "The Three-Body Problem", "isbn": "978-0765382030", "genre": "Science Fiction", "price": 11.99, "published_date": "2008-01-01", "in_stock": true, "authors": [{"name": "Liu Cixin", "born_year": 1963}], "reviews": [{"customer": "Carol Williams", "rating": 5, "body": "Hard sci-fi that reads like a thriller. Liu is extraordinary."}, {"customer": "Noah Fischer", "rating": 4, "body": "The physics is real and the stakes are cosmic."}, {"customer": "Tyler Brooks", "rating": 3, "body": "The Cultural Revolution sections are gripping. The VR game parts drag."}, {"customer": "Xavier Dubois", "rating": 2, "body": "Flat characters and infodumps. The science can'\''t carry a novel alone."}], "tags": ["physics", "alien", "china", "first-contact", "civilization"]}'

put_doc "book:the-dark-forest" '{"type": "book", "title": "The Dark Forest", "isbn": "978-0765386694", "genre": "Science Fiction", "price": 12.49, "published_date": "2008-05-01", "in_stock": true, "authors": [{"name": "Liu Cixin", "born_year": 1963}], "reviews": [{"customer": "Carol Williams", "rating": 5, "body": "The Dark Forest theory is the most terrifying idea in sci-fi."}, {"customer": "Rashid Kouri", "rating": 4, "body": "Better than the first book. Luo Ji'\''s arc is brilliant."}, {"customer": "Yuki Mori", "rating": 3, "body": "The wallfacer concept is great but the execution meanders."}], "tags": ["dark-forest", "deterrence", "alien", "strategy", "civilization"]}'

put_doc "book:deaths-end" '{"type": "book", "title": "Death'\''s End", "isbn": "978-0765386632", "genre": "Science Fiction", "price": 12.99, "published_date": "2010-11-01", "in_stock": true, "authors": [{"name": "Liu Cixin", "born_year": 1963}], "reviews": [{"customer": "Noah Fischer", "rating": 4, "body": "Mind-blowing scope. The fairy tale section is haunting."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Ambitious but the time jumps made it hard to stay invested."}], "tags": ["cosmology", "dimensions", "sacrifice", "time", "civilization"]}'

put_doc "book:rebecca" '{"type": "book", "title": "Rebecca", "isbn": "978-0380730407", "genre": "Mystery", "price": 9.99, "published_date": "1938-01-01", "in_stock": true, "authors": [{"name": "Daphne du Maurier", "born_year": 1907}], "reviews": [{"customer": "Iris Novak", "rating": 4, "body": "Gothic suspense at its finest. Rebecca haunts every page."}, {"customer": "Olivia Santos", "rating": 5, "body": "Last night I dreamt I went to Manderley again. Perfection."}, {"customer": "Quinn Murphy", "rating": 3, "body": "The narrator'\''s passivity got frustrating. Just stand up for yourself!"}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Du Maurier builds atmosphere like a master painter."}], "tags": ["gothic", "mansion", "jealousy", "suspense", "identity"]}'

put_doc "book:my-cousin-rachel" '{"type": "book", "title": "My Cousin Rachel", "isbn": "978-0380731541", "genre": "Mystery", "price": 9.49, "published_date": "1951-01-01", "in_stock": true, "authors": [{"name": "Daphne du Maurier", "born_year": 1907}], "reviews": [{"customer": "Olivia Santos", "rating": 3, "body": "Atmospheric but not as compelling as Rebecca."}, {"customer": "Wendy Zhao", "rating": 4, "body": "The ambiguity of Rachel'\''s true nature is maddening. In a good way."}], "tags": ["suspicion", "inheritance", "love", "poison", "ambiguity"]}'

put_doc "book:the-name-of-the-wind" '{"type": "book", "title": "The Name of the Wind", "isbn": "978-0756404741", "genre": "Fantasy", "price": 12.99, "published_date": "2007-03-27", "in_stock": true, "authors": [{"name": "Patrick Rothfuss", "born_year": 1973}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "Kvothe'\''s story is addictive. I need the third book."}, {"customer": "Grace Kim", "rating": 4, "body": "Beautifully written fantasy. The magic system is elegant."}, {"customer": "Jamal Washington", "rating": 5, "body": "Rothfuss crafts prose like poetry. A stunning debut."}, {"customer": "Priya Sharma", "rating": 2, "body": "Kvothe is a Mary Sue. Good at everything, loved by everyone. Boring."}, {"customer": "Viktor Petrov", "rating": 3, "body": "Beautiful writing but the unreliable narrator angle needs a payoff."}], "tags": ["magic", "university", "music", "legend", "coming-of-age"]}'

put_doc "book:the-wise-mans-fear" '{"type": "book", "title": "The Wise Man'\''s Fear", "isbn": "978-0756407919", "genre": "Fantasy", "price": 13.99, "published_date": "2011-03-01", "in_stock": true, "authors": [{"name": "Patrick Rothfuss", "born_year": 1973}], "reviews": [{"customer": "Alice Johnson", "rating": 3, "body": "The Felurian section nearly ruined it for me. Uneven."}, {"customer": "Jamal Washington", "rating": 4, "body": "The Adem chapters are fascinating. Still waiting for book three."}], "tags": ["magic", "travel", "martial-arts", "fae", "adventure"]}'

put_doc "book:the-way-of-kings" '{"type": "book", "title": "The Way of Kings", "isbn": "978-0765365279", "genre": "Fantasy", "price": 14.99, "published_date": "2010-08-31", "in_stock": true, "authors": [{"name": "Brandon Sanderson", "born_year": 1975}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "Sanderson'\''s worldbuilding is on another level. Stormlight is epic."}, {"customer": "Elena Rodriguez", "rating": 4, "body": "Long but never boring. Kaladin'\''s arc is incredible."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Impressive scope but the prose is strictly functional."}, {"customer": "Viktor Petrov", "rating": 2, "body": "1000 pages of setup. Nothing happens until the last 200."}], "tags": ["epic", "knights", "storms", "war", "honor"]}'

put_doc "book:words-of-radiance" '{"type": "book", "title": "Words of Radiance", "isbn": "978-0765365286", "genre": "Fantasy", "price": 14.99, "published_date": "2014-03-04", "in_stock": true, "authors": [{"name": "Brandon Sanderson", "born_year": 1975}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "Even better than Way of Kings. The climax is stunning."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Shallan'\''s chapters slow things down considerably."}], "tags": ["epic", "knights", "shardblades", "war", "oaths"]}'

put_doc "book:mistborn-the-final-empire" '{"type": "book", "title": "Mistborn: The Final Empire", "isbn": "978-0765350381", "genre": "Fantasy", "price": 11.99, "published_date": "2006-07-17", "in_stock": true, "authors": [{"name": "Brandon Sanderson", "born_year": 1975}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "A heist novel set in a fantasy world. Brilliant concept."}, {"customer": "Maya Patel", "rating": 5, "body": "Vin is one of the best fantasy protagonists ever."}, {"customer": "Tyler Brooks", "rating": 4, "body": "Fast-paced and clever. The allomancy system is creative."}, {"customer": "Yuki Mori", "rating": 3, "body": "Fun but the writing style is very YA for adult fantasy."}], "tags": ["heist", "allomancy", "rebellion", "ash", "prophecy"]}'

put_doc "book:assassins-apprentice" '{"type": "book", "title": "Assassin'\''s Apprentice", "isbn": "978-0553573398", "genre": "Fantasy", "price": 10.99, "published_date": "1995-03-01", "in_stock": true, "authors": [{"name": "Robin Hobb", "born_year": 1952}], "reviews": [{"customer": "Grace Kim", "rating": 5, "body": "Hobb writes emotional devastation like no one else. Poor Fitz."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "A slow-burn character study wrapped in a fantasy novel. Loved it."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Fitz makes terrible decisions constantly. Hard to root for him."}], "tags": ["assassin", "court", "telepathy", "coming-of-age", "wolves"]}'

put_doc "book:royal-assassin" '{"type": "book", "title": "Royal Assassin", "isbn": "978-0553573411", "genre": "Fantasy", "price": 10.99, "published_date": "1996-03-01", "in_stock": true, "authors": [{"name": "Robin Hobb", "born_year": 1952}], "reviews": [{"customer": "Grace Kim", "rating": 4, "body": "Hobb ramps up the emotional pain. Regal is a great villain."}, {"customer": "Xavier Dubois", "rating": 2, "body": "Fitz suffers nonstop for 600 pages. It'\''s just misery tourism."}], "tags": ["intrigue", "loyalty", "sacrifice", "court", "magic"]}'

put_doc "book:the-blade-itself" '{"type": "book", "title": "The Blade Itself", "isbn": "978-0316387316", "genre": "Fantasy", "price": 11.49, "published_date": "2006-01-01", "in_stock": true, "authors": [{"name": "Joe Abercrombie", "born_year": 1974}], "reviews": [{"customer": "Hassan Ali", "rating": 4, "body": "Grimdark done right. Abercrombie writes fantastic characters."}, {"customer": "Jamal Washington", "rating": 4, "body": "Dark, funny, and brutally subversive of fantasy tropes."}, {"customer": "Sofia Andersson", "rating": 3, "body": "Everyone is terrible and nothing matters. Is that the point?"}], "tags": ["grimdark", "war", "barbarian", "inquisitor", "humor"]}'

put_doc "book:before-they-are-hanged" '{"type": "book", "title": "Before They Are Hanged", "isbn": "978-0316387330", "genre": "Fantasy", "price": 11.49, "published_date": "2007-03-15", "in_stock": true, "authors": [{"name": "Joe Abercrombie", "born_year": 1974}], "reviews": [{"customer": "Hassan Ali", "rating": 3, "body": "Solid middle book but the quest storyline is a letdown."}, {"customer": "Sofia Andersson", "rating": 4, "body": "Glokta'\''s siege chapters are some of the best in the genre."}], "tags": ["grimdark", "quest", "siege", "war", "cynicism"]}'

put_doc "book:last-argument-of-kings" '{"type": "book", "title": "Last Argument of Kings", "isbn": "978-0316387378", "genre": "Fantasy", "price": 11.49, "published_date": "2008-03-20", "in_stock": true, "authors": [{"name": "Joe Abercrombie", "born_year": 1974}], "reviews": [{"customer": "Jamal Washington", "rating": 5, "body": "The most cynical ending in fantasy. Abercrombie is ruthless."}, {"customer": "Sofia Andersson", "rating": 4, "body": "Everything comes together perfectly. Devastating final pages."}], "tags": ["grimdark", "war", "revolution", "betrayal", "consequences"]}'

put_doc "book:the-secret-history" '{"type": "book", "title": "The Secret History", "isbn": "978-1400031702", "genre": "Thriller", "price": 12.99, "published_date": "1992-09-01", "in_stock": true, "authors": [{"name": "Donna Tartt", "born_year": 1963}], "reviews": [{"customer": "Iris Novak", "rating": 5, "body": "A dark academia thriller before dark academia was a thing."}, {"customer": "Liam O'\''Brien", "rating": 5, "body": "Tartt'\''s prose is intoxicating. I couldn'\''t put it down."}, {"customer": "Quinn Murphy", "rating": 4, "body": "The slow unraveling is masterfully done."}, {"customer": "Tyler Brooks", "rating": 3, "body": "These are all terrible people and the book wants me to care. I don'\''t."}], "tags": ["academia", "murder", "classics", "obsession", "guilt"]}'

put_doc "book:the-goldfinch" '{"type": "book", "title": "The Goldfinch", "isbn": "978-0316055444", "genre": "Fiction", "price": 13.99, "published_date": "2013-10-22", "in_stock": true, "authors": [{"name": "Donna Tartt", "born_year": 1963}], "reviews": [{"customer": "Iris Novak", "rating": 4, "body": "Sprawling and immersive. Theo'\''s grief feels so real."}, {"customer": "Xavier Dubois", "rating": 2, "body": "Overwritten and 300 pages too long. The Vegas section is a slog."}, {"customer": "Priya Sharma", "rating": 3, "body": "Ambitious but bloated. Needed a ruthless editor."}], "tags": ["art", "loss", "addiction", "theft", "identity"]}'

put_doc "book:cosmos" '{"type": "book", "title": "Cosmos", "isbn": "978-0345539434", "genre": "Science", "price": 12.49, "published_date": "1980-01-01", "in_stock": true, "authors": [{"name": "Carl Sagan", "born_year": 1934}], "reviews": [{"customer": "Carol Williams", "rating": 5, "body": "Sagan makes the universe feel like home. Pure wonder."}, {"customer": "Noah Fischer", "rating": 5, "body": "Every human should read this book. Sagan at his finest."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Dated in places but the sense of wonder is timeless."}], "tags": ["astronomy", "science", "wonder", "exploration", "universe"]}'

put_doc "book:contact" '{"type": "book", "title": "Contact", "isbn": "978-1501197987", "genre": "Science Fiction", "price": 10.99, "published_date": "1985-09-01", "in_stock": true, "authors": [{"name": "Carl Sagan", "born_year": 1934}], "reviews": [{"customer": "Carol Williams", "rating": 4, "body": "Sagan writes first contact with scientific rigor and heart."}, {"customer": "Yuki Mori", "rating": 3, "body": "The science is fascinating but the novel reads like a screenplay."}], "tags": ["seti", "first-contact", "science", "faith", "signal"]}'

put_doc "book:the-two-towers" '{"type": "book", "title": "The Two Towers", "isbn": "978-0547928203", "genre": "Fantasy", "price": 12.99, "published_date": "1954-11-11", "in_stock": true, "authors": [{"name": "J.R.R. Tolkien", "born_year": 1892}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "The battle of Helm'\''s Deep is unforgettable on the page."}, {"customer": "Grace Kim", "rating": 4, "body": "The split narrative works perfectly. Gollum steals every scene."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Frodo and Sam'\''s trek starts to feel repetitive in this volume."}], "tags": ["quest", "war", "fellowship", "ents", "mordor"]}'

put_doc "book:the-return-of-the-king" '{"type": "book", "title": "The Return of the King", "isbn": "978-0547928197", "genre": "Fantasy", "price": 12.99, "published_date": "1955-10-20", "in_stock": true, "authors": [{"name": "J.R.R. Tolkien", "born_year": 1892}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "The most satisfying ending in all of fantasy literature."}, {"customer": "Grace Kim", "rating": 5, "body": "The Scouring of the Shire is underrated. Perfect conclusion."}, {"customer": "Tyler Brooks", "rating": 3, "body": "Too many false endings. The actual ending is perfect though."}], "tags": ["war", "king", "destiny", "sacrifice", "victory"]}'

put_doc "book:dune-messiah" '{"type": "book", "title": "Dune Messiah", "isbn": "978-0441172696", "genre": "Science Fiction", "price": 9.99, "published_date": "1969-01-01", "in_stock": true, "authors": [{"name": "Frank Herbert", "born_year": 1920}], "reviews": [{"customer": "Elena Rodriguez", "rating": 4, "body": "Herbert deconstructs the hero'\''s journey he built in Dune."}, {"customer": "Viktor Petrov", "rating": 2, "body": "A pale shadow of the original. Where'\''s the adventure?"}], "tags": ["politics", "religion", "conspiracy", "prescience", "empire"]}'

put_doc "book:children-of-dune" '{"type": "book", "title": "Children of Dune", "isbn": "978-0441104024", "genre": "Science Fiction", "price": 9.99, "published_date": "1976-04-01", "in_stock": true, "authors": [{"name": "Frank Herbert", "born_year": 1920}], "reviews": [{"customer": "Elena Rodriguez", "rating": 3, "body": "The Dune universe is rich but this entry feels transitional."}, {"customer": "Priya Sharma", "rating": 3, "body": "Interesting themes about transformation but a slow read."}], "tags": ["empire", "transformation", "ecology", "twins", "destiny"]}'

put_doc "book:and-then-there-were-none" '{"type": "book", "title": "And Then There Were None", "isbn": "978-0062073488", "genre": "Mystery", "price": 9.99, "published_date": "1939-11-06", "in_stock": true, "authors": [{"name": "Agatha Christie", "born_year": 1890}], "reviews": [{"customer": "Frank Okafor", "rating": 5, "body": "The greatest mystery novel ever written. Perfection."}, {"customer": "Iris Novak", "rating": 5, "body": "Christie at the peak of her powers. Absolutely gripping."}, {"customer": "Quinn Murphy", "rating": 4, "body": "Devoured it in one sitting. The nursery rhyme is haunting."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Clever but the characters are just puzzle pieces, not people."}], "tags": ["island", "murder", "suspense", "isolation", "nursery-rhyme"]}'

put_doc "book:the-murder-of-roger-ackroyd" '{"type": "book", "title": "The Murder of Roger Ackroyd", "isbn": "978-0062073563", "genre": "Mystery", "price": 9.49, "published_date": "1926-06-01", "in_stock": true, "authors": [{"name": "Agatha Christie", "born_year": 1890}], "reviews": [{"customer": "Frank Okafor", "rating": 5, "body": "The twist! Christie broke all the rules and got away with it."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Controversial ending but you have to admire the audacity."}, {"customer": "Yuki Mori", "rating": 2, "body": "The twist feels like cheating. I felt robbed, not impressed."}], "tags": ["poirot", "village", "twist", "narrator", "deception"]}'

put_doc "book:foundation-and-empire" '{"type": "book", "title": "Foundation and Empire", "isbn": "978-0553293371", "genre": "Science Fiction", "price": 8.99, "published_date": "1952-01-01", "in_stock": true, "authors": [{"name": "Isaac Asimov", "born_year": 1920}], "reviews": [{"customer": "Hassan Ali", "rating": 4, "body": "The Mule is one of the great sci-fi antagonists."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Good sequel but the surprise factor from the first book is gone."}], "tags": ["empire", "mutant", "psychohistory", "war", "surprise"]}'

put_doc "book:second-foundation" '{"type": "book", "title": "Second Foundation", "isbn": "978-0553293364", "genre": "Science Fiction", "price": 8.99, "published_date": "1953-01-01", "in_stock": true, "authors": [{"name": "Isaac Asimov", "born_year": 1920}], "reviews": [{"customer": "Hassan Ali", "rating": 4, "body": "The search for the Second Foundation is a great cat-and-mouse."}, {"customer": "Noah Fischer", "rating": 3, "body": "Mind games upon mind games. A bit exhausting by the end."}], "tags": ["psychohistory", "mind-control", "secrecy", "search", "plan"]}'

put_doc "book:i-robot" '{"type": "book", "title": "I, Robot", "isbn": "978-0553294385", "genre": "Science Fiction", "price": 8.49, "published_date": "1950-12-02", "in_stock": true, "authors": [{"name": "Isaac Asimov", "born_year": 1920}], "reviews": [{"customer": "Dan Chen", "rating": 4, "body": "The Three Laws of Robotics are still the gold standard."}, {"customer": "Keiko Tanaka", "rating": 5, "body": "Each story is a perfect logic puzzle. Asimov was a master."}, {"customer": "Sofia Andersson", "rating": 3, "body": "Clever but formulaic. Each story follows the same template."}], "tags": ["robots", "AI", "laws", "ethics", "logic"]}'

put_doc "book:a-wizard-of-earthsea" '{"type": "book", "title": "A Wizard of Earthsea", "isbn": "978-0547722023", "genre": "Fantasy", "price": 8.99, "published_date": "1968-11-01", "in_stock": true, "authors": [{"name": "Ursula K. Le Guin", "born_year": 1929}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "Le Guin'\''s Earthsea is just as important as Middle-earth."}, {"customer": "Liam O'\''Brien", "rating": 4, "body": "A coming-of-age story with real depth. Beautiful world."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Short and simple. Good for younger readers but felt slight to me."}], "tags": ["magic", "coming-of-age", "shadow", "islands", "naming"]}'

put_doc "book:the-dispossessed" '{"type": "book", "title": "The Dispossessed", "isbn": "978-0061054884", "genre": "Science Fiction", "price": 11.49, "published_date": "1974-05-01", "in_stock": true, "authors": [{"name": "Ursula K. Le Guin", "born_year": 1929}], "reviews": [{"customer": "Elena Rodriguez", "rating": 5, "body": "Le Guin at her political best. A true ambiguous utopia."}, {"customer": "Viktor Petrov", "rating": 3, "body": "More interested in political theory than telling a story."}], "tags": ["anarchism", "utopia", "physics", "revolution", "dual-world"]}'

put_doc "book:coraline" '{"type": "book", "title": "Coraline", "isbn": "978-0380807345", "genre": "Horror", "price": 7.99, "published_date": "2002-08-01", "in_stock": true, "authors": [{"name": "Neil Gaiman", "born_year": 1960}], "reviews": [{"customer": "Grace Kim", "rating": 4, "body": "Gaiman writes children'\''s horror better than anyone alive."}, {"customer": "Olivia Santos", "rating": 5, "body": "Genuinely creepy. The Other Mother still gives me nightmares."}, {"customer": "Tyler Brooks", "rating": 3, "body": "Good for kids but too short and simple for an adult reader."}], "tags": ["other-mother", "buttons", "bravery", "children", "dark"]}'

put_doc "book:neverwhere" '{"type": "book", "title": "Neverwhere", "isbn": "978-0060557812", "genre": "Fantasy", "price": 10.99, "published_date": "1996-09-16", "in_stock": true, "authors": [{"name": "Neil Gaiman", "born_year": 1960}], "reviews": [{"customer": "Grace Kim", "rating": 5, "body": "London Below is one of Gaiman'\''s best creations."}, {"customer": "Priya Sharma", "rating": 3, "body": "Fun urban fantasy but felt rushed compared to American Gods."}], "tags": ["london-below", "urban-fantasy", "quest", "underworld", "doors"]}'

put_doc "book:the-ocean-at-the-end-of-the-lane" '{"type": "book", "title": "The Ocean at the End of the Lane", "isbn": "978-0062255655", "genre": "Fantasy", "price": 9.99, "published_date": "2013-06-18", "in_stock": true, "authors": [{"name": "Neil Gaiman", "born_year": 1960}], "reviews": [{"customer": "Alice Johnson", "rating": 4, "body": "Gaiman'\''s most personal novel. Small in scope but immense in feeling."}, {"customer": "Yuki Mori", "rating": 3, "body": "Lovely but insubstantial. More of a novella than a novel."}], "tags": ["childhood", "memory", "magic", "fear", "sacrifice"]}'

put_doc "book:mort" '{"type": "book", "title": "Mort", "isbn": "978-0062225719", "genre": "Fantasy", "price": 8.49, "published_date": "1987-11-12", "in_stock": true, "authors": [{"name": "Terry Pratchett", "born_year": 1948}], "reviews": [{"customer": "Alice Johnson", "rating": 5, "body": "Death as a character is Pratchett'\''s greatest invention."}, {"customer": "Dan Chen", "rating": 4, "body": "Funny, philosophical, and weirdly touching. Classic Discworld."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Fun but the humor overshadows any real emotional stakes."}], "tags": ["death", "discworld", "apprentice", "humor", "duty"]}'

put_doc "book:guards-guards" '{"type": "book", "title": "Guards! Guards!", "isbn": "978-0062225757", "genre": "Fantasy", "price": 8.99, "published_date": "1989-11-01", "in_stock": true, "authors": [{"name": "Terry Pratchett", "born_year": 1948}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "Vimes is the best character in fantasy. Period."}, {"customer": "Maya Patel", "rating": 5, "body": "Pratchett'\''s Night Watch books are criminally underrated."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Pratchett at his most satirical. The dragon reveal is genius."}, {"customer": "Viktor Petrov", "rating": 2, "body": "I don'\''t get the Discworld hype. The humor is too British for me."}], "tags": ["discworld", "dragon", "city-watch", "humor", "vimes"]}'

put_doc "book:small-gods" '{"type": "book", "title": "Small Gods", "isbn": "978-0062237378", "genre": "Fantasy", "price": 8.49, "published_date": "1992-05-01", "in_stock": true, "authors": [{"name": "Terry Pratchett", "born_year": 1948}], "reviews": [{"customer": "Dan Chen", "rating": 5, "body": "Pratchett'\''s sharpest satire of religion. Brutha is wonderful."}, {"customer": "Liam O'\''Brien", "rating": 4, "body": "Standalone Discworld at its best. The tortoise scenes are gold."}, {"customer": "Yuki Mori", "rating": 3, "body": "The philosophy is interesting but the jokes slow the pace."}], "tags": ["discworld", "religion", "philosophy", "humor", "tortoise"]}'

put_doc "book:going-postal" '{"type": "book", "title": "Going Postal", "isbn": "978-0060502935", "genre": "Fantasy", "price": 9.49, "published_date": "2004-09-28", "in_stock": true, "authors": [{"name": "Terry Pratchett", "born_year": 1948}], "reviews": [{"customer": "Bob Smith", "rating": 5, "body": "Moist von Lipwig is one of Pratchett'\''s best creations."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "A con artist running the post office. Only Pratchett."}], "tags": ["discworld", "con-artist", "post-office", "humor", "redemption"]}'

put_doc "book:the-hobbit" '{"type": "book", "title": "The Hobbit", "isbn": "978-0547928227", "genre": "Fantasy", "price": 10.99, "published_date": "1937-09-21", "in_stock": true, "authors": [{"name": "J.R.R. Tolkien", "born_year": 1892}], "reviews": [{"customer": "Carol Williams", "rating": 5, "body": "Where it all began. Bilbo'\''s adventure is pure magic."}, {"customer": "Jamal Washington", "rating": 5, "body": "A perfect adventure story for all ages."}, {"customer": "Olivia Santos", "rating": 4, "body": "Charming and cozy. Tolkien at his most accessible."}, {"customer": "Sofia Andersson", "rating": 3, "body": "A children'\''s book. Fine for what it is but nothing groundbreaking."}], "tags": ["dragon", "treasure", "adventure", "dwarves", "hobbit"]}'

put_doc "book:pet-sematary" '{"type": "book", "title": "Pet Sematary", "isbn": "978-1501156700", "genre": "Horror", "price": 10.49, "published_date": "1983-11-14", "in_stock": true, "authors": [{"name": "Stephen King", "born_year": 1947}], "reviews": [{"customer": "Hassan Ali", "rating": 5, "body": "King'\''s scariest novel. Sometimes dead is better."}, {"customer": "Noah Fischer", "rating": 4, "body": "Dread builds slowly and never lets up."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Effective but King telegraphs every scare well in advance."}], "tags": ["burial-ground", "death", "grief", "resurrection", "dread"]}'

put_doc "book:salems-lot" '{"type": "book", "title": "Salem'\''s Lot", "isbn": "978-0307743671", "genre": "Horror", "price": 9.99, "published_date": "1975-10-17", "in_stock": true, "authors": [{"name": "Stephen King", "born_year": 1947}], "reviews": [{"customer": "Bob Smith", "rating": 4, "body": "King'\''s take on vampires is genuinely frightening."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Slow start but the last third is relentless."}], "tags": ["vampires", "small-town", "evil", "night", "writer"]}'

put_doc "book:the-caves-of-steel" '{"type": "book", "title": "The Caves of Steel", "isbn": "978-0553293401", "genre": "Science Fiction", "price": 8.49, "published_date": "1954-01-01", "in_stock": true, "authors": [{"name": "Isaac Asimov", "born_year": 1920}], "reviews": [{"customer": "Keiko Tanaka", "rating": 4, "body": "Asimov'\''s robot detective series is underappreciated."}, {"customer": "Xavier Dubois", "rating": 3, "body": "Good mystery but the future society feels unconvincing."}], "tags": ["robots", "detective", "future-city", "partnership", "prejudice"]}'

put_doc "book:the-naked-sun" '{"type": "book", "title": "The Naked Sun", "isbn": "978-0553293395", "genre": "Science Fiction", "price": 8.49, "published_date": "1957-01-01", "in_stock": true, "authors": [{"name": "Isaac Asimov", "born_year": 1920}], "reviews": [{"customer": "Keiko Tanaka", "rating": 3, "body": "Interesting social concepts but even slower than Caves of Steel."}, {"customer": "Noah Fischer", "rating": 4, "body": "The agoraphobia angle makes Solaria a fascinating detective setting."}], "tags": ["robots", "solaria", "agoraphobia", "isolation", "murder"]}'

put_doc "book:persuasion" '{"type": "book", "title": "Persuasion", "isbn": "978-0141439686", "genre": "Romance", "price": 6.99, "published_date": "1817-12-01", "in_stock": true, "authors": [{"name": "Jane Austen", "born_year": 1775}], "reviews": [{"customer": "Iris Novak", "rating": 5, "body": "Austen'\''s most mature work. Captain Wentworth'\''s letter is perfection."}, {"customer": "Priya Sharma", "rating": 4, "body": "The most emotionally rich Austen novel. Anne deserves the world."}, {"customer": "Tyler Brooks", "rating": 2, "body": "Everyone is so polite about their misery. Just talk to each other!"}], "tags": ["regency", "second-chance", "navy", "constancy", "maturity"]}'

put_doc "book:mansfield-park" '{"type": "book", "title": "Mansfield Park", "isbn": "978-0141439808", "genre": "Romance", "price": 7.49, "published_date": "1814-07-01", "in_stock": true, "authors": [{"name": "Jane Austen", "born_year": 1775}], "reviews": [{"customer": "Iris Novak", "rating": 3, "body": "The quietest Austen. Fanny is hard to root for compared to Lizzy."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Well-crafted but Fanny Price is the least interesting Austen heroine."}], "tags": ["morality", "adoption", "theater", "class", "quiet-strength"]}'

put_doc "book:ubik" '{"type": "book", "title": "Ubik", "isbn": "978-0547572291", "genre": "Science Fiction", "price": 9.99, "published_date": "1969-01-01", "in_stock": true, "authors": [{"name": "Philip K. Dick", "born_year": 1928}], "reviews": [{"customer": "Dan Chen", "rating": 4, "body": "PKD'\''s most disturbing novel. Reality itself decays."}, {"customer": "Rashid Kouri", "rating": 5, "body": "The best Philip K. Dick novel. Nothing else captures his paranoia so well."}], "tags": ["reality", "entropy", "afterlife", "paranoia", "consumerism"]}'

put_doc "book:valis" '{"type": "book", "title": "VALIS", "isbn": "978-0547572414", "genre": "Science Fiction", "price": 10.49, "published_date": "1981-02-01", "in_stock": true, "authors": [{"name": "Philip K. Dick", "born_year": 1928}], "reviews": [{"customer": "Dan Chen", "rating": 3, "body": "Fascinating but nearly impenetrable. PKD at his most unhinged."}, {"customer": "Viktor Petrov", "rating": 1, "body": "Incoherent ramblings dressed up as science fiction. Unreadable."}], "tags": ["theology", "madness", "gnosticism", "reality", "autobiography"]}'

put_doc "book:the-illustrated-man" '{"type": "book", "title": "The Illustrated Man", "isbn": "978-1451678185", "genre": "Science Fiction", "price": 9.49, "published_date": "1951-02-01", "in_stock": true, "authors": [{"name": "Ray Bradbury", "born_year": 1920}], "reviews": [{"customer": "Frank Okafor", "rating": 4, "body": "Bradbury'\''s imagination in short form. Every story is a gem."}, {"customer": "Liam O'\''Brien", "rating": 5, "body": "The Veldt alone makes this collection essential."}, {"customer": "Wendy Zhao", "rating": 3, "body": "Some stories are brilliant, others are forgettable."}], "tags": ["tattoos", "stories", "future", "space", "humanity"]}'

put_doc "book:the-idiot" '{"type": "book", "title": "The Idiot", "isbn": "978-0375702242", "genre": "Fiction", "price": 9.99, "published_date": "1869-01-01", "in_stock": true, "authors": [{"name": "Fyodor Dostoevsky", "born_year": 1821}], "reviews": [{"customer": "Grace Kim", "rating": 4, "body": "Myshkin is one of the most fascinating characters in literature."}, {"customer": "Rashid Kouri", "rating": 3, "body": "Dostoevsky'\''s most frustrating novel. Everyone behaves irrationally."}], "tags": ["innocence", "society", "russia", "compassion", "tragedy"]}'

put_doc "book:sula" '{"type": "book", "title": "Sula", "isbn": "978-1400033430", "genre": "Fiction", "price": 9.99, "published_date": "1973-01-01", "in_stock": true, "authors": [{"name": "Toni Morrison", "born_year": 1931}], "reviews": [{"customer": "Maya Patel", "rating": 4, "body": "Morrison packs an entire world into 174 pages."}, {"customer": "Uma Okonkwo", "rating": 5, "body": "An underappreciated Morrison novel. The friendship is so real."}], "tags": ["friendship", "community", "rebellion", "grief", "identity"]}'

put_doc "book:windpinball" '{"type": "book", "title": "Wind/Pinball", "isbn": "978-0804170147", "genre": "Fiction", "price": 10.49, "published_date": "1979-07-01", "in_stock": true, "authors": [{"name": "Haruki Murakami", "born_year": 1949}], "reviews": [{"customer": "Keiko Tanaka", "rating": 3, "body": "Interesting to see where Murakami started, but very rough."}, {"customer": "Yuki Mori", "rating": 2, "body": "Early Murakami. Not much happens. Very slight."}], "tags": ["youth", "loss", "bars", "japan", "nostalgia"]}'

put_doc "book:dawn" '{"type": "book", "title": "Dawn", "isbn": "978-0446603775", "genre": "Science Fiction", "price": 10.49, "published_date": "1987-01-01", "in_stock": true, "authors": [{"name": "Octavia Butler", "born_year": 1947}], "reviews": [{"customer": "Elena Rodriguez", "rating": 4, "body": "Butler'\''s most challenging work. The Oankali are fascinating."}, {"customer": "Uma Okonkwo", "rating": 4, "body": "Deeply uncomfortable in all the right ways. Consent is the theme."}], "tags": ["alien", "survival", "genetics", "identity", "choice"]}'

put_doc "book:so-long-and-thanks-for-all-the-fish" '{"type": "book", "title": "So Long, and Thanks for All the Fish", "isbn": "978-0345391834", "genre": "Science Fiction", "price": 8.99, "published_date": "1984-11-01", "in_stock": true, "authors": [{"name": "Douglas Adams", "born_year": 1952}], "reviews": [{"customer": "Liam O'\''Brien", "rating": 3, "body": "The weakest Hitchhiker'\''s book. The love story feels off."}, {"customer": "Xavier Dubois", "rating": 2, "body": "Adams clearly ran out of steam. A disappointing sequel."}], "tags": ["humor", "earth", "dolphins", "love", "return"]}'

put_doc "book:mona-lisa-overdrive" '{"type": "book", "title": "Mona Lisa Overdrive", "isbn": "978-0553281743", "genre": "Science Fiction", "price": 10.49, "published_date": "1988-10-01", "in_stock": true, "authors": [{"name": "William Gibson", "born_year": 1948}], "reviews": [{"customer": "Priya Sharma", "rating": 3, "body": "A fitting end to the Sprawl trilogy but the least memorable entry."}], "tags": ["cyberpunk", "AI", "art", "cyberspace", "convergence"]}'

put_doc "book:the-shadow-of-the-wind" '{"type": "book", "title": "The Shadow of the Wind", "isbn": "978-0143034902", "genre": "Mystery", "price": 11.99, "published_date": "2001-04-01", "in_stock": true, "authors": [{"name": "Jorge Luis Borges", "born_year": 1899}], "reviews": [{"customer": "Iris Novak", "rating": 5, "body": "A love letter to books and Barcelona. Atmospheric and gripping."}, {"customer": "Maya Patel", "rating": 4, "body": "Gothic, romantic, and mysterious. A page-turner."}, {"customer": "Quinn Murphy", "rating": 3, "body": "Enjoyable but the plot twists are fairly predictable."}], "tags": ["books", "barcelona", "mystery", "library", "obsession"]}'

put_doc "book:daggerspell" '{"type": "book", "title": "Daggerspell", "isbn": "978-0553565218", "genre": "Fantasy", "price": 8.99, "published_date": "1986-08-01", "in_stock": true, "authors": [{"name": "Robin Hobb", "born_year": 1952}], "reviews": [{"customer": "Jamal Washington", "rating": 4, "body": "Hobb'\''s reincarnation concept is unlike anything else in fantasy."}, {"customer": "Olivia Santos", "rating": 4, "body": "Celtic-inspired fantasy with real emotional depth."}, {"customer": "Yuki Mori", "rating": 3, "body": "The multi-timeline structure is more confusing than illuminating."}], "tags": ["reincarnation", "celtic", "magic", "destiny", "love"]}'

# ---------------------------------------------------------------------------
# Customer documents — a different document type in the same database.
# Document DBs don't enforce a single schema; "type" is just a convention.
# ---------------------------------------------------------------------------
echo "==> Inserting customer documents..."

put_doc "customer:alice" '{"type": "customer", "name": "Alice Johnson", "email": "alice@example.com", "favorites": ["book:dune", "book:the-fellowship-of-the-ring", "book:good-omens", "book:one-hundred-years-of-solitude", "book:things-fall-apart"], "order_history": [{"date": "2023-01-15", "books": ["book:dune", "book:the-fellowship-of-the-ring", "book:one-hundred-years-of-solitude"], "total": 34.97, "status": "delivered"}, {"date": "2023-01-15", "books": ["book:things-fall-apart", "book:the-name-of-the-wind"], "total": 21.98, "status": "delivered"}, {"date": "2023-01-15", "books": ["book:the-two-towers", "book:the-return-of-the-king", "book:the-ocean-at-the-end-of-the-lane", "book:mort"], "total": 44.46, "status": "shipped"}]}'

put_doc "customer:bob" '{"type": "customer", "name": "Bob Smith", "email": "bob@example.com", "favorites": ["book:good-omens", "book:the-shining", "book:the-hitchhikers-guide-to-the-galaxy", "book:neuromancer", "book:the-way-of-kings"], "order_history": [{"date": "2023-02-20", "books": ["book:good-omens", "book:the-hitchhikers-guide-to-the-galaxy"], "total": 36.97, "status": "delivered"}, {"date": "2023-02-20", "books": ["book:neuromancer", "book:the-way-of-kings", "book:words-of-radiance", "book:guards-guards"], "total": 59.45, "status": "shipped"}, {"date": "2023-02-20", "books": ["book:the-shining", "book:salems-lot"], "total": 19.98, "status": "delivered"}]}'

put_doc "customer:carol" '{"type": "customer", "name": "Carol Williams", "email": "carol@example.com", "favorites": ["book:the-fellowship-of-the-ring", "book:2001-a-space-odyssey", "book:the-three-body-problem", "book:the-dark-forest", "book:cosmos"], "order_history": [{"date": "2023-03-05", "books": ["book:foundation", "book:2001-a-space-odyssey", "book:the-three-body-problem", "book:the-dark-forest"], "total": 42.46, "status": "delivered"}, {"date": "2023-03-05", "books": ["book:brave-new-world", "book:the-old-man-and-the-sea", "book:cosmos", "book:contact"], "total": 52.45, "status": "pending"}]}'

put_doc "customer:dan" '{"type": "customer", "name": "Dan Chen", "email": "dan@example.com", "favorites": ["book:1984", "book:do-androids-dream-of-electric-sheep", "book:slaughterhouse-five", "book:the-brothers-karamazov", "book:the-hitchhikers-guide-to-the-galaxy"], "order_history": [{"date": "2023-03-18", "books": ["book:1984", "book:do-androids-dream-of-electric-sheep", "book:slaughterhouse-five", "book:the-brothers-karamazov"], "total": 43.96, "status": "delivered"}, {"date": "2023-03-18", "books": ["book:the-trial", "book:mistborn-the-final-empire", "book:i-robot", "book:mort"], "total": 46.45, "status": "delivered"}, {"date": "2023-03-18", "books": ["book:the-hitchhikers-guide-to-the-galaxy", "book:ubik", "book:valis"], "total": 29.47, "status": "shipped"}]}'

put_doc "customer:elena" '{"type": "customer", "name": "Elena Rodriguez", "email": "elena@example.com", "favorites": ["book:dune", "book:the-left-hand-of-darkness", "book:pride-and-prejudice", "book:the-handmaids-tale", "book:kindred"], "order_history": [{"date": "2023-04-02", "books": ["book:dune", "book:the-left-hand-of-darkness", "book:pride-and-prejudice", "book:kindred"], "total": 39.96, "status": "delivered"}, {"date": "2023-04-02", "books": ["book:the-handmaids-tale", "book:the-fifth-season", "book:the-obelisk-gate", "book:dune-messiah"], "total": 75.43, "status": "shipped"}]}'

put_doc "customer:frank" '{"type": "customer", "name": "Frank Okafor", "email": "frank@example.com", "favorites": ["book:murder-on-the-orient-express", "book:animal-farm", "book:one-hundred-years-of-solitude", "book:and-then-there-were-none", "book:the-murder-of-roger-ackroyd"], "order_history": [{"date": "2023-05-10", "books": ["book:murder-on-the-orient-express", "book:animal-farm", "book:one-hundred-years-of-solitude", "book:frankenstein"], "total": 37.96, "status": "delivered"}, {"date": "2023-05-10", "books": ["book:the-martian-chronicles", "book:the-call-of-cthulhu", "book:things-fall-apart", "book:for-whom-the-bell-tolls"], "total": 64.43, "status": "delivered"}]}'

put_doc "customer:grace" '{"type": "customer", "name": "Grace Kim", "email": "grace@example.com", "favorites": ["book:the-fellowship-of-the-ring", "book:the-color-of-magic", "book:crime-and-punishment", "book:ficciones", "book:assassins-apprentice"], "order_history": [{"date": "2023-05-22", "books": ["book:the-fellowship-of-the-ring", "book:the-color-of-magic", "book:crime-and-punishment", "book:ficciones"], "total": 48.45, "status": "delivered"}, {"date": "2023-05-22", "books": ["book:kafka-on-the-shore", "book:the-name-of-the-wind", "book:assassins-apprentice", "book:royal-assassin"], "total": 88.42, "status": "pending"}]}'

put_doc "customer:hassan" '{"type": "customer", "name": "Hassan Ali", "email": "hassan@example.com", "favorites": ["book:foundation", "book:1984", "book:fahrenheit-451", "book:brave-new-world", "book:pet-sematary"], "order_history": [{"date": "2023-06-14", "books": ["book:foundation", "book:1984", "book:rendezvous-with-rama", "book:fahrenheit-451"], "total": 47.45, "status": "delivered"}, {"date": "2023-06-14", "books": ["book:it", "book:brave-new-world", "book:neuromancer", "book:the-blade-itself"], "total": 85.42, "status": "shipped"}]}'

put_doc "customer:iris" '{"type": "customer", "name": "Iris Novak", "email": "iris@example.com", "favorites": ["book:pride-and-prejudice", "book:the-handmaids-tale", "book:frankenstein", "book:the-secret-history", "book:and-then-there-were-none"], "order_history": [{"date": "2023-07-01", "books": ["book:murder-on-the-orient-express", "book:pride-and-prejudice", "book:emma", "book:the-handmaids-tale"], "total": 57.93, "status": "delivered"}, {"date": "2023-07-01", "books": ["book:one-hundred-years-of-solitude", "book:love-in-the-time-of-cholera", "book:rebecca", "book:the-secret-history"], "total": 81.93, "status": "delivered"}]}'

put_doc "customer:jamal" '{"type": "customer", "name": "Jamal Washington", "email": "jamal@example.com", "favorites": ["book:beloved", "book:blood-meridian", "book:the-road", "book:the-name-of-the-wind", "book:last-argument-of-kings"], "order_history": [{"date": "2023-07-30", "books": ["book:the-fellowship-of-the-ring", "book:american-gods", "book:the-man-in-the-high-castle", "book:beloved"], "total": 61.95, "status": "delivered"}, {"date": "2023-07-30", "books": ["book:the-stand", "book:blood-meridian", "book:the-name-of-the-wind", "book:the-blade-itself"], "total": 79.93, "status": "pending"}]}'

put_doc "customer:keiko" '{"type": "customer", "name": "Keiko Tanaka", "email": "keiko@example.com", "favorites": ["book:the-metamorphosis", "book:i-robot"], "order_history": [{"date": "2023-08-12", "books": ["book:dune", "book:do-androids-dream-of-electric-sheep", "book:crime-and-punishment", "book:norwegian-wood"], "total": 71.43, "status": "delivered"}, {"date": "2023-08-12", "books": ["book:i-robot", "book:the-caves-of-steel", "book:the-naked-sun"], "total": 25.47, "status": "shipped"}]}'

put_doc "customer:liam" '{"type": "customer", "name": "Liam O'\''Brien", "email": "liam@example.com", "favorites": ["book:the-left-hand-of-darkness", "book:slaughterhouse-five", "book:the-secret-history", "book:the-illustrated-man"], "order_history": [{"date": "2023-09-01", "books": ["book:the-left-hand-of-darkness", "book:animal-farm", "book:slaughterhouse-five", "book:notes-from-underground"], "total": 36.96, "status": "delivered"}, {"date": "2023-09-01", "books": ["book:the-hitchhikers-guide-to-the-galaxy", "book:the-restaurant-at-the-end-of-the-universe", "book:the-trial", "book:the-secret-history"], "total": 75.92, "status": "delivered"}]}'

put_doc "customer:maya" '{"type": "customer", "name": "Maya Patel", "email": "maya@example.com", "favorites": ["book:good-omens", "book:beloved", "book:the-fifth-season", "book:the-stone-sky", "book:mistborn-the-final-empire"], "order_history": [{"date": "2023-09-25", "books": ["book:good-omens", "book:pride-and-prejudice", "book:the-handmaids-tale", "book:parable-of-the-sower"], "total": 77.43, "status": "delivered"}, {"date": "2023-09-25", "books": ["book:mistborn-the-final-empire", "book:guards-guards", "book:the-shadow-of-the-wind"], "total": 32.97, "status": "shipped"}]}'

put_doc "customer:noah" '{"type": "customer", "name": "Noah Fischer", "email": "noah@example.com", "favorites": ["book:it", "book:2001-a-space-odyssey", "book:the-road", "book:cosmos"], "order_history": [{"date": "2023-10-10", "books": ["book:dune", "book:foundation", "book:it", "book:2001-a-space-odyssey"], "total": 61.94, "status": "delivered"}, {"date": "2023-10-10", "books": ["book:the-three-body-problem", "book:deaths-end", "book:cosmos", "book:second-foundation"], "total": 65.44, "status": "delivered"}]}'

put_doc "customer:olivia" '{"type": "customer", "name": "Olivia Santos", "email": "olivia@example.com", "favorites": ["book:the-shining", "book:norwegian-wood", "book:the-old-man-and-the-sea", "book:rebecca", "book:coraline"], "order_history": [{"date": "2023-11-05", "books": ["book:1984", "book:the-shining", "book:fahrenheit-451", "book:norwegian-wood"], "total": 59.44, "status": "delivered"}, {"date": "2023-11-05", "books": ["book:the-old-man-and-the-sea", "book:coraline", "book:the-hobbit", "book:daggerspell"], "total": 35.96, "status": "pending"}]}'

put_doc "customer:priya" '{"type": "customer", "name": "Priya Sharma", "email": "priya@example.com", "favorites": [], "order_history": [{"date": "2023-11-20", "books": ["book:dune", "book:american-gods", "book:sense-and-sensibility", "book:crime-and-punishment"], "total": 50.95, "status": "delivered"}, {"date": "2023-11-20", "books": ["book:kindred", "book:brave-new-world", "book:mrs-dalloway", "book:neuromancer"], "total": 92.91, "status": "shipped"}, {"date": "2023-11-20", "books": ["book:the-stand", "book:oryx-and-crake"], "total": 23.98, "status": "pending"}]}'

put_doc "customer:quinn" '{"type": "customer", "name": "Quinn Murphy", "email": "quinn@example.com", "favorites": ["book:misery"], "order_history": [{"date": "2023-12-03", "books": ["book:murder-on-the-orient-express", "book:1984", "book:a-scanner-darkly", "book:misery"], "total": 62.44, "status": "delivered"}, {"date": "2023-12-03", "books": ["book:at-the-mountains-of-madness", "book:blood-meridian", "book:no-country-for-old-men", "book:the-metamorphosis"], "total": 71.43, "status": "delivered"}, {"date": "2023-12-03", "books": ["book:and-then-there-were-none", "book:a-wizard-of-earthsea", "book:salems-lot", "book:the-shadow-of-the-wind"], "total": 40.96, "status": "shipped"}]}'

put_doc "customer:rashid" '{"type": "customer", "name": "Rashid Kouri", "email": "rashid@example.com", "favorites": ["book:ubik"], "order_history": [{"date": "2024-01-08", "books": ["book:the-fellowship-of-the-ring", "book:animal-farm", "book:do-androids-dream-of-electric-sheep", "book:childhoods-end"], "total": 50.45, "status": "delivered"}, {"date": "2024-01-08", "books": ["book:the-brothers-karamazov", "book:norwegian-wood", "book:the-road", "book:ficciones"], "total": 75.93, "status": "delivered"}, {"date": "2024-01-08", "books": ["book:the-two-towers", "book:mort", "book:ubik", "book:the-idiot"], "total": 41.46, "status": "shipped"}]}'

put_doc "customer:sofia" '{"type": "customer", "name": "Sofia Andersson", "email": "sofia@example.com", "favorites": [], "order_history": [{"date": "2024-01-22", "books": ["book:foundation", "book:the-color-of-magic", "book:emma", "book:2001-a-space-odyssey"], "total": 54.44, "status": "delivered"}, {"date": "2024-01-22", "books": ["book:blood-meridian", "book:mrs-dalloway", "book:the-fifth-season", "book:the-stone-sky"], "total": 75.43, "status": "delivered"}]}'

put_doc "customer:tyler" '{"type": "customer", "name": "Tyler Brooks", "email": "tyler@example.com", "favorites": [], "order_history": [{"date": "2024-02-14", "books": ["book:the-fellowship-of-the-ring", "book:the-left-hand-of-darkness", "book:pride-and-prejudice", "book:it"], "total": 62.94, "status": "delivered"}, {"date": "2024-02-14", "books": ["book:kafka-on-the-shore", "book:frankenstein", "book:ficciones", "book:the-old-man-and-the-sea"], "total": 70.43, "status": "delivered"}, {"date": "2024-02-14", "books": ["book:the-return-of-the-king", "book:coraline", "book:persuasion"], "total": 27.97, "status": "shipped"}]}'

put_doc "customer:uma" '{"type": "customer", "name": "Uma Okonkwo", "email": "uma@example.com", "favorites": ["book:kindred", "book:things-fall-apart", "book:sula"], "order_history": [{"date": "2024-03-01", "books": ["book:good-omens", "book:the-shining", "book:oryx-and-crake", "book:the-martian-chronicles"], "total": 67.44, "status": "delivered"}, {"date": "2024-03-01", "books": ["book:kindred", "book:things-fall-apart", "book:for-whom-the-bell-tolls", "book:rebecca"], "total": 73.93, "status": "delivered"}, {"date": "2024-03-01", "books": ["book:guards-guards", "book:going-postal", "book:sula", "book:dawn"], "total": 38.96, "status": "pending"}]}'

put_doc "customer:viktor" '{"type": "customer", "name": "Viktor Petrov", "email": "viktor@example.com", "favorites": [], "order_history": [{"date": "2024-03-15", "books": ["book:dune", "book:the-fellowship-of-the-ring", "book:the-color-of-magic", "book:a-scanner-darkly"], "total": 72.43, "status": "delivered"}, {"date": "2024-03-15", "books": ["book:beloved", "book:the-hitchhikers-guide-to-the-galaxy", "book:at-the-mountains-of-madness", "book:brave-new-world"], "total": 73.43, "status": "delivered"}, {"date": "2024-03-15", "books": ["book:the-way-of-kings", "book:dune-messiah", "book:the-dispossessed", "book:guards-guards"], "total": 55.95, "status": "cancelled"}]}'

put_doc "customer:wendy" '{"type": "customer", "name": "Wendy Zhao", "email": "wendy@example.com", "favorites": [], "order_history": [{"date": "2024-04-02", "books": ["book:murder-on-the-orient-express", "book:1984", "book:the-man-in-the-high-castle", "book:the-handmaids-tale"], "total": 81.92, "status": "delivered"}, {"date": "2024-04-02", "books": ["book:to-the-lighthouse", "book:neuromancer", "book:the-obelisk-gate", "book:deaths-end"], "total": 92.41, "status": "delivered"}]}'

put_doc "customer:xavier" '{"type": "customer", "name": "Xavier Dubois", "email": "xavier@example.com", "favorites": ["book:no-country-for-old-men"], "order_history": [{"date": "2024-04-18", "books": ["book:foundation", "book:american-gods", "book:pride-and-prejudice", "book:cats-cradle"], "total": 60.94, "status": "delivered"}, {"date": "2024-04-18", "books": ["book:brave-new-world", "book:no-country-for-old-men", "book:a-farewell-to-arms", "book:the-three-body-problem"], "total": 80.43, "status": "delivered"}, {"date": "2024-04-18", "books": ["book:foundation-and-empire", "book:the-caves-of-steel", "book:so-long-and-thanks-for-all-the-fish", "book:daggerspell"], "total": 35.46, "status": "shipped"}]}'

put_doc "customer:yuki" '{"type": "customer", "name": "Yuki Mori", "email": "yuki@example.com", "favorites": [], "order_history": [{"date": "2024-05-01", "books": ["book:good-omens", "book:do-androids-dream-of-electric-sheep", "book:it", "book:rendezvous-with-rama"], "total": 82.43, "status": "delivered"}, {"date": "2024-05-01", "books": ["book:song-of-solomon", "book:1q84", "book:frankenstein", "book:the-road"], "total": 71.43, "status": "delivered"}, {"date": "2024-05-01", "books": ["book:mistborn-the-final-empire", "book:contact", "book:the-murder-of-roger-ackroyd", "book:the-ocean-at-the-end-of-the-lane"], "total": 70.43, "status": "pending"}]}'

# ---------------------------------------------------------------------------
# Design document with MapReduce views — CouchDB's query mechanism.
# ---------------------------------------------------------------------------
echo "==> Creating design document (views)..."

put_doc "_design/bookstore" '{
  "views": {
    "books_by_genre": {
      "map": "function(doc) { if (doc.type === '\''book'\'') emit(doc.genre, {title: doc.title, price: doc.price}); }"
    },
    "avg_rating": {
      "map": "function(doc) { if (doc.type === '\''book'\'' && doc.reviews) { doc.reviews.forEach(function(r) { emit(doc._id, r.rating); }); } }",
      "reduce": "_stats"
    }
  }
}'

echo "==> CouchDB seeding complete."
echo ""
echo "Try these queries:"
echo "  docker compose exec seed curl -s http://launchpad:dontdothis@document:5984/bookstore/book:dune"
echo "  docker compose exec seed curl -s 'http://launchpad:dontdothis@document:5984/bookstore/_design/bookstore/_view/books_by_genre?key=\"Science Fiction\"'"
